// === Expedition ===
//! import "D:\Work\GitHub\Test\System\CardModelPack.j"
//! import "D:\Work\GitHub\Test\Data\Data_PrototypeStats.j"
//! import "D:\Work\GitHub\Test\Data\Data_PrototypeCatalog.j"
//! import "D:\Work\GitHub\Test\Data\Data_PrototypeCardImages.j"
//! import "D:\Work\GitHub\Test\Data\Data_PrototypeGrowth.j"
//! import "D:\Work\GitHub\Test\System\CardRecovery.j"
//! import "D:\Work\GitHub\Test\Data\Data_Prototype.j"
//! import "D:\Work\GitHub\Test\System\ExpeditionPrototype.j"
//! import "D:\Work\GitHub\Test\UI\UI_ExpeditionPrototype.j"
//! import "D:\Work\GitHub\Test\Data\Data_Expedition.j"
//! import "D:\Work\GitHub\Test\Data\Data_ExpeditionEvents.j"
//! import "D:\Work\GitHub\Test\Data\Data_ExpeditionRewards.j"
//! import "D:\Work\GitHub\Test\System\ExpeditionEffects.j"
//! import "D:\Work\GitHub\Test\System\ExpeditionCombat.j"
//! import "D:\Work\GitHub\Test\System\Expedition.j"
//! import "D:\Work\GitHub\Test\UI\UI_ExpeditionCommon.j"
//! import "D:\Work\GitHub\Test\UI\UI_ExpeditionChoice.j"
//! import "D:\Work\GitHub\Test\UI\UI_PrototypeStatus.j"
//! import "D:\Work\GitHub\Test\UI\UI_PrototypeCards.j"
//! import "D:\Work\GitHub\Test\UI\UI_ExpeditionStats.j"

// === UI ===
//! import "D:\Work\GitHub\Test\UI\UI_InputGate.j"
//! import "D:\Work\GitHub\Test\UI\UI_BossHP.j"
//! import "D:\Work\GitHub\Test\UI\UI_BossEnd.j"
//! import "D:\Work\GitHub\Test\UI\UI_BossStart.j"
//! import "D:\Work\GitHub\Test\UI\UI_CastingBar.j"
//! import "D:\Work\GitHub\Test\UI\UI_Enchant.j"
//! import "D:\Work\GitHub\Test\UI\UI_HP.j"
//! import "D:\Work\GitHub\Test\UI\UI_Info.j"
//! import "D:\Work\GitHub\Test\UI\UI_Item.j"
//! import "D:\Work\GitHub\Test\UI\UI_MainQuest.j"
//! import "D:\Work\GitHub\Test\UI\UI_Msg.j"
//! import "D:\Work\GitHub\Test\UI\UI_Pick.j"
//! import "D:\Work\GitHub\Test\UI\UI_Skill.j"
//! import "D:\Work\GitHub\Test\UI\UI_SkillHUD.j"
//! import "D:\Work\GitHub\Test\UI\UI_SkillLevel.j"
//! import "D:\Work\GitHub\Test\UI\UI_Stone.j"
//! import "D:\Work\GitHub\Test\UI\UI_Tip.j"
//! import "D:\Work\GitHub\Test\UI\UI_Shop.j"
//! import "D:\Work\GitHub\Test\UI\UI_OFF.j"
//! import "D:\Work\GitHub\Test\UI\UI_Quest.j"
//! import "D:\Work\GitHub\Test\UI\UI_Arcana.j"
//! import "D:\Work\GitHub\Test\UI\UI_V.j"
//! import "D:\Work\GitHub\Test\UI\UI_Map.j"
//! import "D:\Work\GitHub\Test\UI\UI_Emoji.j"
//! import "D:\Work\GitHub\Test\UI\UI_FPS.j"
//! import "D:\Work\GitHub\Test\UI\MemUI.j"
//! import "D:\Work\GitHub\Test\UI\UI_Info2.j"
//! import "D:\Work\GitHub\Test\UI\UI_Overlay.j"
//! import "D:\Work\GitHub\Test\UI\UI_BigWheel.j"
//! import "D:\Work\GitHub\Test\UI\UI_Elixir.j"
//! import "D:\Work\GitHub\Test\UI\UI_Upgrade.j"

// === Content ===
//! import "D:\Work\GitHub\Test\content\NPC.j"
//! import "D:\Work\GitHub\Test\content\TimeOfDay.j"

// === Library ===
//! import "D:\Work\GitHub\Test\Library\Stun.j"
//! import "D:\Work\GitHub\Test\Library\AttackAngle.j"
//! import "D:\Work\GitHub\Test\Library\DummyMagicleash.j"
//! import "D:\Work\GitHub\Test\Library\CameraShaker.j"
//! import "D:\Work\GitHub\Test\Library\AnimationTime.j"
//! import "D:\Work\GitHub\Test\Library\Knockback.j"
//! import "D:\Work\GitHub\Test\Library\BGMSound.j"
//! import "D:\Work\GitHub\Test\Library\EffectDummy.j"
//! import "D:\Work\GitHub\Test\Library\Airbourne.j"
//! import "D:\Work\GitHub\Test\Library\EXSetEffectXYHook.j"
//! import "D:\Work\GitHub\Test\Library\TimerSleep.j"
//! import "D:\Work\GitHub\Test\Library\ArrayEx.j"
//! import "D:\Work\GitHub\Test\Library\TimerUtils.j"
//! import "D:\Work\GitHub\Test\Library\Splash.j"
//! import "D:\Work\GitHub\Test\Library\IntegerPool.j"
//! import "D:\Work\GitHub\Test\Library\AngleDistancePolar.j"
//! import "D:\Work\GitHub\Test\Library\Struct2Buff.j"
//! import "D:\Work\GitHub\Test\Library\UnitIndexer.j"
//! import "D:\Work\GitHub\Test\Library\Tick.j"
//! import "D:\Work\GitHub\Test\Library\Text.j"
//! import "D:\Work\GitHub\Test\Library\Add.j"
//! import "D:\Work\GitHub\Test\Library\SafePos.j"
//! import "D:\Work\GitHub\Test\Library\AddonCameraDistance.j"
//! import "D:\Work\GitHub\Test\Library\AOE.j"
//! import "D:\Work\GitHub\Test\Library\CustomEvent.j"
//! import "D:\Work\GitHub\Test\Library\Missile.j"
//! import "D:\Work\GitHub\Test\Library\UnitAlpha.j"
//! import "D:\Work\GitHub\Test\Library\ClosestUnit.j"
//! import "D:\Work\GitHub\Test\Library\PointToPolygon.j"
//! import "D:\Work\GitHub\Test\Library\FrameCount.j"
//! import "D:\Work\GitHub\Test\Library\FrameGrid.j"
//! import "D:\Work\GitHub\Test\Library\Sort.j"
//! import "D:\Work\GitHub\Test\Library\PauseUnit.j"

// === Library: memory ===
//! import "D:\Work\GitHub\Test\Library\Memory\02-APIBasicUtils.j"
//! import "D:\Work\GitHub\Test\Library\Memory\03-APITypecast.j"
//! import "D:\Work\GitHub\Test\Library\Memory\MemoryLib.j"

// === Data ===
//! import "D:\Work\GitHub\Test\Data\Native.j"
//! import "D:\Work\GitHub\Test\Data\Data_Arcana.j"
//! import "D:\Work\GitHub\Test\Data\Data_Item.j"
//! import "D:\Work\GitHub\Test\Data\Data_Unit.j"
//! import "D:\Work\GitHub\Test\Data\Data_Map.j"
//! import "D:\Work\GitHub\Test\Data\Data_Buff.j"

// === Hero ===
//! import "D:\Work\GitHub\Test\Hero\SkillDash.j"
//! import "D:\Work\GitHub\Test\Hero\SkillButton.j"
//! import "D:\Work\GitHub\Test\Hero\Potion.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenQ.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenW.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenE.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenR.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenA.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenS.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenD.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenF.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenV.j"
//! import "D:\Work\GitHub\Test\Hero\Chen\HeroChenC.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoQ.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoW.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoE.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoR.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoA.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoS.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoD.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoF.j"
//! import "D:\Work\GitHub\Test\Hero\Momizi\HeroMoV.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaQ.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaW.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaE.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaR.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaA.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaS.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaD.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaF.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaV.j"
//! import "D:\Work\GitHub\Test\Hero\Lucia\HeroLuciaZ.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarQ.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarW.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarE.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarR.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarA.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarS.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarD.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarF.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarV.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarC.j"
//! import "D:\Work\GitHub\Test\Hero\Narmaya\HeroNarZ.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiA.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiC.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiD.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiE.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiF.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiQ.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiR.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiS.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiV.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiW.j"
//! import "D:\Work\GitHub\Test\Hero\Bandi\HeroBandiZ.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegData.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegCore.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegC.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegF.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegQ.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegW.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegE.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegR.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegA.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegS.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegD.j"
//! import "D:\Work\GitHub\Test\Hero\Siegfried\HeroSiegZ.j"

// === Boss ===
//! import "D:\Work\GitHub\Test\Boss\Boss1-1.j"
//! import "D:\Work\GitHub\Test\Boss\Boss1-2.j"
//! import "D:\Work\GitHub\Test\Boss\Boss1-3.j"
//! import "D:\Work\GitHub\Test\Boss\Boss1-4.j"
//! import "D:\Work\GitHub\Test\Boss\BossAOESandbag.j"
//! import "D:\Work\GitHub\Test\Boss\BossAggro.j"
//! import "D:\Work\GitHub\Test\Boss\BossArcher.j"

// === System ===
//! import "D:\Work\GitHub\Test\System\FileSave.j"
//! import "D:\Work\GitHub\Test\System\Init.j"
//! import "D:\Work\GitHub\Test\System\ItemPickUp.j"
//! import "D:\Work\GitHub\Test\System\Cooldown.j"
//! import "D:\Work\GitHub\Test\System\SaveLoad.j"
//! import "D:\Work\GitHub\Test\System\Shield.j"
//! import "D:\Work\GitHub\Test\System\StatsSetting.j"
//! import "D:\Work\GitHub\Test\System\DamageEffect.j"
//! import "D:\Work\GitHub\Test\System\DamageEffectBoss.j"
//! import "D:\Work\GitHub\Test\System\Market.j"
//! import "D:\Work\GitHub\Test\System\Daily.j"
//! import "D:\Work\GitHub\Test\System\ITEM.j"
//! import "D:\Work\GitHub\Test\System\PlayerState.j"
//! import "D:\Work\GitHub\Test\System\Filter.j"

// === Library: external API ===
// duplicate direct import removed: JNStashNet.j is imported by the map script

// === Root: ESC ===
//! import "D:\Work\GitHub\Test\ESC.j"

