-- 실제 출력 호출에서 추출한 문장 틀로 값과 이름을 보존하여 번역한다.
local entries = {
  {pattern="^【收割概率】([%+%-]?[%d%.]+)%%%(%+([%+%-]?[%d%.]+)%%每波%)$",parts={"【수확 확률】",{index=1,numeric=true},"% (웨이브마다 +",{index=2,numeric=true},"%)"}},
  {pattern="^【反抗概率】([%+%-]?[%d%.]+)%%$",parts={"【저항 확률】",{index=1,numeric=true},"%"}},
  {pattern="^%[神秘花园%]获得([%d]+)积分$",parts={"[신비한 정원] 포인트 ",{index=1,player=false,numeric=true}," 획득"}},
  {pattern="^%[神秘花园%]获得([%d]+)追忆值$",parts={"[신비한 정원] 추억 수치 ",{index=1,player=false,numeric=true}," 획득"}},
  {pattern="^%[神秘花园%]获得补给$",parts={"[신비한 정원] 보급품 획득"}},
  {pattern="^%[神秘花园%]获得([%d]+)属性$",parts={"[신비한 정원] 무작위 능력치 ",{index=1,player=false,numeric=true}," 증가"}},
  {pattern="^%[神秘花园%]获得([%d%.]+)%%伤害加成$",parts={"[신비한 정원] 피해 증가 ",{index=1,player=false,numeric=true},"% 획득"}},
  {pattern="^%[神秘花园%]获得遗物$",parts={"[신비한 정원] 유물 획득"}},
  {pattern="^八云紫：第一座世界之门已被破坏，请在(.-)秒内破坏剩余的世界之门，否则所有世界之门都会重新构筑，请抓紧时间$",parts={"야쿠모 유카리. 첫 번째 세계의 문이 파괴됐어. 남은 시간은",{index=1,player=false,numeric=false},"초 안에 남은 세계의 문을 파괴하세요. 실패하면 모든 문이 재구축됩니다. 서두르세요."}},
  {pattern="^灵魂之力达到临界,灵魂阶级提升%(当前灵魂阶级(.-)%):\n%[提升2神力承载\n提升0%.5神化位%]$",parts={"영혼의 힘이 임계에 도달하여 영혼 등급 증가(현재 영혼 등급",{index=1,player=false,numeric=false},"):\n[신력 수용량 2 증가\n신화 슬롯 0.5 증가]"}},
  {pattern="^灵魂之力达到临界,灵魂阶级提升%(当前灵魂阶级(.-)%):\n%[提升2神力承载\n提升1神化位%]$",parts={"영혼의 힘이 임계에 도달하여 영혼 등급 증가(현재 영혼 등급",{index=1,player=false,numeric=false},"):\n[신력 수용량 2 증가\n신화 슬롯 1 증가]"}},
  {pattern="^(.-)，我豹子头零充与你自幼相交，今日倒来害我，怎不干你事！且吃我一晒。$",parts={{index=1,player=true,numeric=false},", 나는 무과금 표범머리요! 어릴 때부터 알고 지낸 사이인데 오늘 나를 해치려 드는가! 이 자랑이나 받아라!"}},
  {pattern="^大地的凛冽已经有所觉悟，(.-)为了最后的战斗解放了所剩无几的生命。$",parts={"대지의 혹독함을 이미 각오했으니,",{index=1,player=true,numeric=false},"마지막 싸움을 위해 얼마 남지 않은 생명을 해방했습니다."}},
  {pattern="^(.-):『(.-)，知道要去哪里了吗？如果是下地狱的话，代我向阎王问好。』$",parts={{index=1,player=false,numeric=false},":『",{index=2,player=false,numeric=false},", 어디로 갈지 알겠나? 지옥에 간다면 염라대왕에게 안부 전해 줘.』"}},
  {pattern="^能源转换完成：消耗 (.-)×([%+%-]?[%d%.eE]+)  → 能量 %+([%+%-]?[%d%.eE]+)；剩余(.-)：([%+%-]?[%d%.eE]+)；当前能量：([%+%-]?[%d%.eE]+)$",parts={"에너지 변환 완료. ",{index=1,player=false,numeric=false},"×",{index=2,player=false,numeric=true}," 소모 → 에너지 +",{index=3,player=false,numeric=true},". 남은 ",{index=4,player=false,numeric=false},". ",{index=5,player=false,numeric=true},". 현재 에너지 ",{index=6,player=false,numeric=true},""}},
  {pattern="^%[庭院之门%]住客反抗激烈,收割(.-)失败,提升下一次收割概率$",parts={"[정원의 문] 투숙객이 격렬히 저항합니다. 수확",{index=1,player=false,numeric=false},"실패, 다음 수확 확률 증가"}},
  {pattern="^(.-) 发电效率:(.-)/秒 消耗燃料:%[(.-)%] 燃料持续时间:(.-)秒$",parts={"",{index=1,player=false,numeric=false}," 발전 효율.",{index=2,player=false,numeric=false},"/초 소모 연료.[",{index=3,player=false,numeric=false},"] 연료 지속시간.",{index=4,player=false,numeric=false},"초"}},
  {pattern="^(.-)%[学级裁判%]先招募6名不同学生，发现尸体后才能调查$",parts={{index=1,player=false,numeric=false},"[학급재판] 서로 다른 학생 6명을 모집하고 시체를 발견한 후 조사할 수 있습니다"}},
  {pattern="^等待地图初始化中……\n版本号：(.-)\n版权模型请勿擅自使用$",parts={"맵 초기화를 기다리는 중……\n","버전. ",{index=1,player=false,numeric=false},"\n저작권이 있는 모델을 무단으로 사용하지 마세요."}},
  {pattern="^%[格里芬公司%]公司等级:([%+%-]?[%d%.eE]+) 发展度:([%+%-]?[%d%.eE]+)%% 仓库:([%+%-]?[%d%.eE]+)/([%+%-]?[%d%.eE]+)$",parts={"[그리폰 회사] 회사 레벨. ",{index=1,player=false,numeric=true}," / 발전도. ",{index=2,player=false,numeric=true},"","%"," / 창고. ",{index=3,player=false,numeric=true},"/",{index=4,player=false,numeric=true},""}},
  {pattern="^粉色妖精小姐吃掉了你的积分!!!\n当前成功率:(.-)%%$",parts={"분홍 요정 아가씨가 포인트를 먹어 버렸습니다!!!\n현재 성공률.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^%[金毛脆脆鲨%-爱与美女神的加护%]提升([%+%-]?[%d%.]+%%?)点全属性$",parts={"[금발 아기 상어 - 사랑과 미의 여신의 가호] 증가",{index=1,player=false,numeric=true},"모든 능력치"}},
  {pattern="^(.-)结束了冒险，达成结局《我已经厌倦了,再见了爱丽丝》$",parts={{index=1,player=true,numeric=false},"모험 종료, 결말 《이제 지쳤어, 안녕 앨리스》 달성"}},
  {pattern="^%[灵光一闪%],失败补救回来了,进度改变:(.-)%%$",parts={"[번뜩이는 영감] 실패를 만회했습니다. 진도 변화.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^(.-)%[风云%]主修三门武学全部圆满后才能兼修另一线$",parts={{index=1,player=false,numeric=false},"[풍운] 주 수련 무공 세 가지를 모두 완성해야 다른 계통을 함께 수련할 수 있습니다"}},
  {pattern="^给三国杀刷出六星好评，获得100元宝，当前元宝:([%+%-]?[%d%.eE]+)$",parts={"삼국살에 별 여섯 개 리뷰를 남겨 원보 100 획득, 현재 원보. ",{index=1,player=false,numeric=true},""}},
  {pattern="^%[稀世珍宝%]获得一次免费十连机会，当前次数:([%+%-]?[%d%.eE]+)$",parts={"[희세의 보물] 무료 열 번 뽑기 기회 획득, 현재 횟수. ",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)的矿石病彻底爆发了，生命进入了最后的倒计时……$",parts={{index=1,player=true,numeric=false},"의 광석병이 완전히 발병했습니다. 생명의 마지막 순간이 다가옵니다……"}},
  {pattern="^%[灵光一闪%],进度迅速推进,进度改变:(.-)%%$",parts={"[번뜩이는 영감] 진도가 급격히 진행되었습니다. 진도 변화.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^%[系统%]击败BOSS,灵魂之力提升%(当前灵魂之力([%+%-]?[%d%.]+%%?)点%)$",parts={"[시스템] BOSS 격파, 영혼의 힘 증가(현재 영혼의 힘",{index=1,player=false,numeric=true},"포인트)"}},
  {pattern="^%[孔涛罗%]与%[(.-)%]同归于尽,无法继续复仇$",parts={"[쿵 타오뤄]와 [",{index=1,player=false,numeric=false},"]와 함께 사망하여 복수를 계속할 수 없습니다"}},
  {pattern="^提升%[([%+%-]?[%d%.eE]+)%%%*机械变异%]终结减伤%(上限([%+%-]?[%d%.eE]+)%%%)$",parts={"최종 피해 감소 [",{index=1,player=false,numeric=true},"","%","*기계 변이] 증가(최대 ",{index=2,player=false,numeric=true},"","%",")"}},
  {pattern="^%[([%+%-]?[%d%.eE]+)%%%*女仆变异数量%]物品获取数量%+1$",parts={"[",{index=1,player=false,numeric=true},"","%","*메이드 변이 수] 확률로 아이템 획득 수량 +1"}},
  {pattern="^(.-)对(.-)打出了超越极限的一斩,造成了%[([%+%-]?[%d%.]+%%?)%]点伤害$",parts={{index=1,player=true,numeric=false},"대상 ",{index=2,player=false,numeric=false},"한계를 초월하는 참격으로 [",{index=3,player=false,numeric=true},"]의 피해"}},
  {pattern="^(.-)对(.-)打出了超越极限的一击,造成了%[([%+%-]?[%d%.]+%%?)%]点伤害$",parts={{index=1,player=true,numeric=false},"대상 ",{index=2,player=false,numeric=false},"한계를 초월하는 일격으로 [",{index=3,player=false,numeric=true},"]의 피해"}},
  {pattern="^%[格里芬公司%-营收%]盈利:([%+%-]?[%d%.]+%%?) 任务收益:([%+%-]?[%d%.]+%%?)$",parts={"[그리폰 회사-매출] 수익.",{index=1,player=false,numeric=true}," 임무 보상.",{index=2,player=false,numeric=true},""}},
  {pattern="^%[庭院之门%]获得(.-)点外域物质与(.-)积分%(当前([%+%-]?[%d%.]+%%?)点%)$",parts={"[정원의 문] 획득",{index=1,player=false,numeric=false},"외역 물질과",{index=2,player=false,numeric=false},"포인트(현재",{index=3,player=false,numeric=true},"포인트)"}},
  {pattern="^%[分车检测%] 已分车：玩家([%+%-]?[%d%.eE]+)随机校验不一致$",parts={"[동기화 검사] 연결이 분리되었습니다. 플레이어 ",{index=1,player=false,numeric=true},"의 난수 검증 불일치"}},
  {pattern="^降低%[([%+%-]?[%d%.eE]+)%%%]对%[噬星灾神%]造成的伤害$",parts={"[별을 삼키는 재앙신]에게 주는 피해 [",{index=1,player=false,numeric=true},"","%","] 감소"}},
  {pattern="^受到来自%[噬星灾神%]伤害提升%[([%+%-]?[%d%.eE]+)%%%]$",parts={"[별을 삼키는 재앙신]에게 받는 피해 [",{index=1,player=false,numeric=true},"","%","] 증가"}},
  {pattern="^连一刻都没有为(.-)的死亡哀悼，立刻赶到战场的是(.-)$",parts={"한순간도",{index=1,player=false,numeric=false},"의 죽음을 애도하지 않고, 곧바로 전장에 도착한 자는",{index=2,player=false,numeric=false}}},
  {pattern="^你从%[无尽黄金袋%]中获得了 (.-) 可用积分$",parts={"[끝없는 황금 주머니]에서 획득했습니다 ",{index=1,player=false,numeric=false}," 사용 가능 포인트"}},
  {pattern="^%[宇宙联合行星保护机构%]降低承载消耗:(.-)$",parts={"[우주 연합 행성 보호 기관] 수용량 소모 감소.",{index=1,player=false,numeric=false}}},
  {pattern="^— 能源转换台 —  | 每次最多消耗: ([%+%-]?[%d%.eE]+)$",parts={"— 에너지 변환대 —  | 회당 최대 소모량 ",{index=1,player=false,numeric=true},""}},
  {pattern="^搜查目标已标记：坐标 ([%+%-]?[%d%.eE]+)，([%+%-]?[%d%.eE]+)，进入 ([%+%-]?[%d%.eE]+) 码范围。$",parts={"수색 대상 표시 완료. 좌표 ",{index=1,player=false,numeric=true},", ",{index=2,player=false,numeric=true},"의 ",{index=3,player=false,numeric=true}," 범위 안으로 진입하세요."}},
  {pattern="^%[全力氪金%]获得500元宝，当前元宝:([%+%-]?[%d%.eE]+)$",parts={"[전력 과금] 원보 500 획득, 현재 원보. ",{index=1,player=false,numeric=true},""}},
  {pattern="^%[系统%]贷款偿还([%+%-]?[%d%.eE]+)积分,还剩余([%+%-]?[%d%.eE]+)积分未偿还$",parts={"[시스템] 대출 ",{index=1,player=false,numeric=true},"포인트 상환, 미상환 잔액 ",{index=2,player=false,numeric=true},"포인트"}},
  {pattern="^(.-)(.-)：Lv([%+%-]?[%d%.eE]+) %-> Lv([%+%-]?[%d%.eE]+)，枪械基础伤害%+([%+%-]?[%d%.eE]+)%%$",parts={"",{index=1,player=false,numeric=false},"",{index=2,player=false,numeric=false},". Lv",{index=3,player=false,numeric=true}," -> Lv",{index=4,player=false,numeric=true},", 총기 기본 피해 +",{index=5,player=false,numeric=true},"","%",""}},
  {pattern="^(.-)因为偷窃被粉色妖精小姐吊起来点天灯了……$",parts={{index=1,player=true,numeric=false},"도둑질을 하다가 분홍 요정 아가씨에게 붙잡혀 매달린 채 불태워졌습니다……"}},
  {pattern="^%[宇宙联合行星保护机构%]不计入承载:(.-)$",parts={"[우주 연합 행성 보호 기관] 수용량에 포함하지 않음.",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)的小蓝天资聪慧！提前进修毕业！为她庆贺！$",parts={{index=1,player=true,numeric=false},"의 라돈은 천재! 조기 수료했습니다! 축하해 주세요!"}},
  {pattern="^%[圣火女神%]女神之力%-提升(.-)点全属性$",parts={"[성화의 여신] 여신의 힘 - 증가",{index=1,player=false,numeric=false},"모든 능력치"}},
  {pattern="^(.-)%[风云%]本次启动已卸载，不能重复启动$",parts={{index=1,player=false,numeric=false},"[풍운] 이번 기동은 해제되어 다시 기동할 수 없습니다"}},
  {pattern="^%[庭院之门%]天亮了，昨晚(.-) 被杀害了！$",parts={"[정원의 문] 날이 밝았습니다. 어젯밤에는",{index=1,player=false,numeric=false}," 살해당했습니다!"}},
  {pattern="^%[庭院之门%]收割(.-)失败%((.-)%%成功率%)$",parts={"[정원의 문] 수확",{index=1,player=false,numeric=false},"실패(",{index=2,player=false,numeric=false},"% 성공률)"}},
  {pattern="^提升%[([%+%-]?[%d%.eE]+)%%%*女仆变异数量%]额外移速$",parts={"추가 이동 속도 [",{index=1,player=false,numeric=true},"","%","*메이드 변이 수] 증가"}},
  {pattern="^已导出详细 DPS 清单 → tloc\\(.-)$",parts={"상세 DPS 목록 내보내기 완료 → tloc\\",{index=1,player=false,numeric=false},""}},
  {pattern="^当前元宝:([%+%-]?[%d%.eE]+)  史诗宝珠:([%+%-]?[%d%.eE]+)  元宝树每秒:([%+%-]?[%d%.eE]+)$",parts={"현재 원보. ",{index=1,player=false,numeric=true}," / 영웅 보주. ",{index=2,player=false,numeric=true}," / 원보 나무 초당 생산량. ",{index=3,player=false,numeric=true},""}},
  {pattern="^我氪命三郎(.-),今日献祭节操,换来我之志成$",parts={"목숨까지 거는 나",{index=1,player=true,numeric=false},", 오늘 정조를 바쳐 소원을 이루리라"}},
  {pattern="^%[分裂银币%] 使你获得了额外积分：(.-)$",parts={"[분열 은화]로 추가 포인트 획득.",{index=1,player=false,numeric=false}}},
  {pattern="^%[分裂金币%] 为你带来了额外积分：(.-)$",parts={"[분열 금화]로 추가 포인트 획득.",{index=1,player=false,numeric=false}}},
  {pattern="^%[千矢%-占卜师试炼%]提升([%+%-]?[%d%.]+%%?)点全属性$",parts={"[치야 - 점술사 시련] 증가",{index=1,player=false,numeric=true},"모든 능력치"}},
  {pattern="^%[第十层鬼域%]决死次数恢复，当前：([%+%-]?[%d%.]+%%?)$",parts={"[열 번째 귀역] 결사 횟수 회복. 현재 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^%[神秘庭院%]下一次做活动所需积分:(.-)$",parts={"[신비한 정원] 다음 행사에 필요한 포인트.",{index=1,player=false,numeric=false}}},
  {pattern="^%[神秘庭院%]住客上限提升,当前上限([%+%-]?[%d%.]+%%?)$",parts={"[신비한 정원] 투숙객 상한 증가, 현재 상한",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)结束了冒险，达成结局《G「end」%(小红帽%)》$",parts={{index=1,player=true,numeric=false},"모험 종료, 결말 《G「end」(빨간 모자)》 달성"}},
  {pattern="^(.-)结束了冒险，达成结局《F「end」%(莉耶芙%)》$",parts={{index=1,player=true,numeric=false},"모험 종료, 결말 《F「end」(리프)》 달성"}},
  {pattern="^请选择科研效果参数%((.-)秒后自动选择%)$",parts={"연구 효과 설정을 선택하세요(",{index=1,player=false,numeric=false},"초 후 자동 선택)"}},
  {pattern="^请选择初始科研方案%((.-)秒后自动选择%)$",parts={"초기 연구 방안을 선택하세요(",{index=1,player=false,numeric=false},"초 후 자동 선택)"}},
  {pattern="^%[哭泣天使%]神泣%-提升([%+%-]?[%d%.]+%%?)点全属性$",parts={"[우는 천사] 신의 눈물 - 증가",{index=1,player=false,numeric=true},"모든 능력치"}},
  {pattern="^%[庭院之门%]入住了新的住客%((.-)%)$",parts={"[정원의 문] 새로운 투숙객 입주(",{index=1,player=false,numeric=false},")"}},
  {pattern="^%[庭院之门%]没有足够的住房给(.-)居住$",parts={"[정원의 문] 남은 방이 부족한 대상",{index=1,player=false,numeric=false},"거주"}},
  {pattern="^%[格里芬公司%]公司发展度提升([%+%-]?[%d%.]+%%?)%%$",parts={"[그리폰 회사] 회사 발전도 증가",{index=1,player=false,numeric=true},"%"}},
  {pattern="^学习毒蛇守卫%(W%) %- %[等级 ([%+%-]?[%d%.eE]+)%]$",parts={"독사 수호물 배우기(W) - [레벨 ",{index=1,player=false,numeric=true},"]"}},
  {pattern="^%[撬锁%]开始撬锁%((.-)%),成功率:(.-)$",parts={"[자물쇠 따기] 시작(",{index=1,player=false,numeric=false},"), 성공률 ",{index=2,player=false,numeric=false},""}},
  {pattern="^提升%[([%+%-]?[%d%.eE]+)%%%*天狗变异%]暴击伤害$",parts={"치명타 피해 [",{index=1,player=false,numeric=true},"","%","*텐구 변이] 증가"}},
  {pattern="^提升%[([%+%-]?[%d%.eE]+)%%%*机械变异%]生命上限$",parts={"최대 생명력 [",{index=1,player=false,numeric=true},"","%","*기계 변이] 증가"}},
  {pattern="^积分不足，需要1000积分，当前([%+%-]?[%d%.eE]+)积分$",parts={"포인트 부족, 1000포인트 필요, 현재 ",{index=1,player=false,numeric=true},"포인트"}},
  {pattern="^元宝不足，需要1000元宝，当前([%+%-]?[%d%.eE]+)元宝$",parts={"원보 부족, 1000원보 필요, 현재 ",{index=1,player=false,numeric=true},"원보"}},
  {pattern="^%[幽灵鲨%]肉斩骨断,剩余次数:([%+%-]?[%d%.]+%%?)$",parts={"[스펙터] 육참골단, 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)复仇失败……死于%[刘豪军%]之手$",parts={{index=1,player=true,numeric=false},"복수 실패…… [류 하오쥔]의 손에 사망"}},
  {pattern="^血液源石结晶密度:%[(.-)%](.-)u/ml$",parts={"혈액 오리지늄 결정 밀도.[",{index=1,player=false,numeric=false},"]",{index=2,player=false,numeric=false},"u/ml"}},
  {pattern="^%[撬锁%]经验等级提升,当前:([%+%-]?[%d%.]+%%?)级$",parts={"[자물쇠 따기] 숙련 레벨 증가, 현재.",{index=1,player=false,numeric=true},"레벨"}},
  {pattern="^积分获取%[([%+%-]?[%d%.]+%%?)%%%(([%+%-]?[%d%.]+%%?)%%%)%+([%+%-]?[%d%.]+%%?)%]$",parts={"포인트 획득[",{index=1,player=false,numeric=true},"%(",{index=2,player=false,numeric=true},"%)+",{index=3,player=false,numeric=true},"]"}},
  {pattern="^(.-)因为偷窃被送去了梅比乌斯实验室……$",parts={{index=1,player=true,numeric=false},"도둑질을 하다가 뫼비우스의 실험실로 끌려갔습니다……"}},
  {pattern="^魔王天囚%-BOSS生命上限倍率:(.-)$",parts={"마왕 천수-BOSS 최대 생명력 배율.",{index=1,player=false,numeric=false}}},
  {pattern="^魔王天囚%-BOSS魔王特性数量:(.-)$",parts={"마왕 천수-BOSS 마왕 특성 수.",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)参加Mojar比赛夺下了『冠军』！$",parts={{index=1,player=true,numeric=false},"Mojar 대회에서 『우승』했습니다!"}},
  {pattern="^%[威吕布%]骁武 当前加成:([%+%-]?[%d%.]+%%?)%%$",parts={"[위세의 여포] 효무 현재 증가량.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^%[孔瑞丽%]灵魂碎片%+(.-) 当前:([%+%-]?[%d%.]+%%?)$",parts={"[쿵 루이리] 영혼 조각 +",{index=1,player=false,numeric=false}," 현재.",{index=2,player=false,numeric=true},""}},
  {pattern="^解锁%[第(.-)层鬼域%]，鬼计数提高1$",parts={"해금 [제",{index=1,player=false,numeric=false},"중첩 귀역], 귀신 수치 1 증가"}},
  {pattern="^%[格里芬公司%]回收人形成功%-(.-)$",parts={"[그리폰 회사] 인형 회수 성공-",{index=1,player=false,numeric=false},""}},
  {pattern="^%[格里芬公司%]心智升级成功%-(.-)$",parts={"[그리폰 회사] 마인드맵 업그레이드 성공-",{index=1,player=false,numeric=false},""}},
  {pattern="^%[庭院之门%]剩余主动收割次数:([%+%-]?[%d%.eE]+)$",parts={"[정원의 문] 남은 능동 수확 횟수. ",{index=1,player=false,numeric=true},""}},
  {pattern="^%[环都市%.德丽莎%]病毒点数:([%+%-]?[%d%.eE]+)$",parts={"[환상도시·테레사] 바이러스 포인트. ",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)%. (.-) %- 输出: ([%+%-]?[%d%.]+%%?)%(([%+%-]?[%d%.]+%%?)%%%)$",parts={"",{index=1,player=false,numeric=false},". ",{index=2,player=false,numeric=false}," - 피해량. ",{index=3,player=false,numeric=true},"(",{index=4,player=false,numeric=true},"%)"}},
  {pattern="^(.-)\n以下点击选择一项变异力量获取：$",parts={{index=1,player=false,numeric=false},"\n아래에서 변이의 힘 하나를 클릭하여 획득하세요."}},
  {pattern="^万华镜%-万华：提升(.-)%%伤害修正$",parts={"만화경-만화. 증가량",{index=1,player=false,numeric=false},"%피해 보정"}},
  {pattern="^%[肃正核心%]提升(.-)神力承载上限$",parts={"[숙정 코어] 증가",{index=1,player=false,numeric=false},"신력 수용 상한"}},
  {pattern="^%[力量无序化%]:当前惩罚([%+%-]?[%d%.]+%%?)%%$",parts={"[힘의 무질서화] 현재 페널티",{index=1,player=false,numeric=true},"%"}},
  {pattern="^%[泡影之恋%]提升全队(.-)点全属性$",parts={"[물거품의 사랑] 팀 전체 증가",{index=1,player=false,numeric=false},"모든 능력치"}},
  {pattern="^(.-),你这样是不会有小丛雨喜欢你的。$",parts={{index=1,player=true,numeric=false},", 그러면 작은 무라사메도 널 좋아하지 않을 거야."}},
  {pattern="^(.-)%[学级裁判%]至少需要3条证据$",parts={{index=1,player=false,numeric=false},"[학급재판] 증거가 최소 3개 필요합니다"}},
  {pattern="^%[系统%]剩余可分配蜕皮次数:(.-)$",parts={"[시스템] 남은 탈피 배분 횟수.",{index=1,player=false,numeric=false},""}},
  {pattern="^%[系统%]蜕皮成功%(剩余(.-)次%)%-(.-)$",parts={"[시스템] 탈피 성공(남은 횟수",{index=1,player=false,numeric=false},"회)-",{index=2,player=false,numeric=false}}},
  {pattern="^(.-)结束了冒险，达成结局《参加茶会》$",parts={{index=1,player=true,numeric=false},"모험 종료, 결말 《다과회 참가》 달성"}},
  {pattern="^%[抉择，抉择%]剩余生效次数：([%+%-]?[%d%.]+%%?)$",parts={"[선택, 또 선택] 남은 발동 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^%[庭院之门%]昨晚反抗的住客:(.-)$",parts={"[정원의 문] 어젯밤 저항한 투숙객.",{index=1,player=false,numeric=false}}},
  {pattern="^%[(.-)%] 完成：(.-) → (.-)；能量消耗([%+%-]?[%d%.eE]+)$",parts={"[",{index=1,player=false,numeric=false},"] 완료. ",{index=2,player=false,numeric=false}," → ",{index=3,player=false,numeric=false},". 에너지 ",{index=4,player=false,numeric=true}," 소모"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%最大生命值$",parts={"[지령전] 최대 생명력 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[搜查%]获得([%+%-]?[%d%.eE]+)条证据，当前([%+%-]?[%d%.eE]+)/6$",parts={"[수색] 증거 ",{index=1,player=false,numeric=true},"개 획득, 현재 ",{index=2,player=false,numeric=true},"/6"}},
  {pattern="^(.-)被达摩克里斯之剑杀死了%(存活了([%+%-]?[%d%.]+%%?)秒%)$",parts={{index=1,player=true,numeric=false},"다모클레스의 검에 사망했습니다(생존 시간",{index=2,player=false,numeric=true},"초)"}},
  {pattern="^科研模式选择超时，自动选择【(.-)】$",parts={"연구 모드 선택 시간 초과, 자동 선택【",{index=1,player=false,numeric=false},"】"}},
  {pattern="^魔王天囚%-怪物生命上限倍率:(.-)$",parts={"마왕 천수-몬스터 최대 생명력 배율.",{index=1,player=false,numeric=false}}},
  {pattern="^魔王天囚%-BOSS伤害倍率:(.-)$",parts={"마왕 천수-BOSS 피해 배율.",{index=1,player=false,numeric=false}}},
  {pattern="^%[宇宙冷漠%]重复生效：【(.-)】$",parts={"[우주의 무관심] 반복 적용.【",{index=1,player=false,numeric=false},"】"}},
  {pattern="^(.-)精神觉醒过程中突破了自身极限%(精神承载上限%+3%)$",parts={{index=1,player=true,numeric=false},"정신 각성 중 자신의 한계를 돌파했습니다(정신 수용 상한 +3)"}},
  {pattern="^(.-)请注意，本关考验你，蒙答案能力$",parts={{index=1,player=true,numeric=false},"주의하세요. 이번 관문은 답을 찍는 능력을 시험합니다"}},
  {pattern="^在下(.-),八十万海豹教头，请多指教$",parts={"소인은",{index=1,player=true,numeric=false},", 팔십만 물개의 교관이오. 잘 부탁하오"}},
  {pattern="^%[第十层鬼域%]决死，剩余：([%+%-]?[%d%.]+%%?)$",parts={"[열 번째 귀역] 결사. 남은 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^购买成功,下一次购买消耗积分:([%+%-]?[%d%.]+%%?)$",parts={"구매 성공, 다음 구매에 필요한 포인트.",{index=1,player=false,numeric=true}}},
  {pattern="^【(.-)】当前蜕皮次数:(.-) 新生次数:(.-)$",parts={"【",{index=1,player=false,numeric=false},"】현재 탈피 횟수.",{index=2,player=false,numeric=false}," 신생 횟수.",{index=3,player=false,numeric=false},""}},
  {pattern="^%[([%+%-]?[%d%.eE]+)%] %+([%+%-]?[%d%.eE]+) 能源 ← (.-)×1$",parts={"[",{index=1,player=false,numeric=true},"] 에너지 +",{index=2,player=false,numeric=true}," ← ",{index=3,player=false,numeric=false},"×1"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%近战伤害$",parts={"[지령전] 근접 피해 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%枪械伤害$",parts={"[지령전] 총기 피해 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%法术伤害$",parts={"[지령전] 주문 피해 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%暴击伤害$",parts={"[지령전] 치명타 피해 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)%%伤害加成$",parts={"[지령전] 피해 보너스 ",{index=1,player=false,numeric=true},"","%"," 증가"}},
  {pattern="^%[庭院之门%]外域物质数量:([%+%-]?[%d%.eE]+)$",parts={"[정원의 문] 외역 물질 수량. ",{index=1,player=false,numeric=true},""}},
  {pattern="^植株年份带来的收益倍率:([%+%-]?[%d%.]+%%?)%%$",parts={"식물의 연령에 따른 보상 배율.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^(.-)告诉少女，她遗忘了重要的记忆$",parts={{index=1,player=true,numeric=false},"소녀에게 중요한 기억을 잊었다고 말합니다."}},
  {pattern="^技术突破项研究完毕:%[(.-)%]$",parts={"기술 돌파 항목 연구 완료.[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^第一刀将在倒计时结束(.-)秒后开始$",parts={"카운트다운이 끝나면 첫 참격이 시작됩니다",{index=1,player=false,numeric=false},"초 후 시작"}},
  {pattern="^星域污染等级提升,当前等级:(.-)$",parts={"성역 오염 레벨 증가, 현재 레벨.",{index=1,player=false,numeric=false},""}},
  {pattern="^你失去了([%+%-]?[%d%.]+%%?)点属性,获得了([%+%-]?[%d%.]+%%?)点属性$",parts={"잃었습니다",{index=1,player=false,numeric=true},"능력치를 소모하여 획득했습니다",{index=2,player=false,numeric=true},"능력치"}},
  {pattern="^地狱の轮祸提升伤害加成：([%+%-]?[%d%.]+%%?)%%$",parts={"지옥의 윤화의 피해 보너스 증가량.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^时螶之鳞逆转时光，她拥(.-)归来。$",parts={"시간 벌레의 비늘이 시간을 되돌리자, 그녀는",{index=1,player=true,numeric=false},"돌아왔다."}},
  {pattern="^%[忍野忍禁忌%]复活剩余(.-)次$",parts={"[오시노 시노부의 금기] 남은 부활 횟수",{index=1,player=false,numeric=false},"회"}},
  {pattern="^%[亚波伦%]剩余复活次数:([%+%-]?[%d%.]+%%?)$",parts={"[아폴리온] 남은 부활 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-),我大概一辈子都不会忘记你吧$",parts={{index=1,player=false,numeric=false},", 아마 평생 당신을 잊지 못하겠군요"}},
  {pattern="^%[抉择，抉择%]重放:【(.-)】$",parts={"[선택, 또 선택] 재현.【",{index=1,player=false,numeric=false},"】"}},
  {pattern="^万华镜%-万华：提升(.-)点全属性$",parts={"만화경-만화. 증가량",{index=1,player=false,numeric=false},"모든 능력치"}},
  {pattern="^%[团子大家族%]提升(.-)点属性$",parts={"[경단 대가족] 증가",{index=1,player=false,numeric=false},"능력치"}},
  {pattern="^%[祸灵梦%]决死剩余次数:([%+%-]?[%d%.]+%%?)$",parts={"[마가 레이무] 결사 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^消耗(.-)个灾祸药剂,召唤魔神人形$",parts={"소모",{index=1,player=false,numeric=false},"개 재앙 물약, 마신 인형 소환"}},
  {pattern="^%[虚空形态%]不计入承载:(.-)$",parts={"[공허 형태] 수용량에 포함하지 않음.",{index=1,player=false,numeric=false}}},
  {pattern="^%[跃影飞绫%-当前类型%]([%+%-]?[%d%.]+%%?)$",parts={"[갬볼 슈라우드 - 현재 유형]",{index=1,player=false,numeric=true}}},
  {pattern="^%[柳叶白菀%-当前属性%]([%+%-]?[%d%.]+%%?)$",parts={"[미르테나스터 - 현재 속성]",{index=1,player=false,numeric=true}}},
  {pattern="^小蓝对(.-)使用了%[星星金币%]$",parts={"라돈의 대상.",{index=1,player=true,numeric=false},"[별의 금화] 사용"}},
  {pattern="^(.-)已被记录%.%.%.%.%.$",parts={{index=1,player=false,numeric=false},"기록되었습니다....."}},
  {pattern="^%[庭院之门%]收租获得(.-)积分$",parts={"[정원의 문] 임대료 수금으로 획득",{index=1,player=false,numeric=false},"포인트"}},
  {pattern="^百合铃分解了邪神酱回收了积分(.-)$",parts={"유리네가 사신 짱을 분해하여 포인트를 회수했습니다",{index=1,player=false,numeric=false},""}},
  {pattern="^%[幻想乡%]邀请了新住客:(.-)$",parts={"[환상향] 새 주민 초대.",{index=1,player=false,numeric=false}}},
  {pattern="^%[恩底弥翁皇国%]魔力计数([%+%-]?[%d%.]+%%?)$",parts={"[엔디미온 황국] 마력 카운터",{index=1,player=false,numeric=true}}},
  {pattern="^—(.-)—|处理数量:([%+%-]?[%d%.eE]+) 能量/次:([%+%-]?[%d%.eE]+)$",parts={"—",{index=1,player=false,numeric=false},"—|처리 수량 ",{index=2,player=false,numeric=true},", 회당 에너지 ",{index=3,player=false,numeric=true},""}},
  {pattern="^%[占卜师试炼%]当前等级:([%+%-]?[%d%.eE]+)$",parts={"[점술사 시련] 현재 레벨. ",{index=1,player=false,numeric=true},""}},
  {pattern="^%[三国杀%]免费十连次数:([%+%-]?[%d%.eE]+)$",parts={"[삼국살] 무료 열 번 뽑기 횟수. ",{index=1,player=false,numeric=true},""}},
  {pattern="^地狱の轮祸提升生命上限：([%+%-]?[%d%.]+%%?)点$",parts={"지옥의 윤화의 최대 생명력 증가량.",{index=1,player=false,numeric=true},""}},
  {pattern="^来自粉色妖精小姐的抚恤金：(.-)$",parts={"분홍 요정 아가씨가 주는 위로금.",{index=1,player=false,numeric=false}}},
  {pattern="^没能让(.-)大人尽兴真的是很抱歉$",parts={"님을",{index=1,player=false,numeric=false},"만족시켜 드리지 못해 정말 죄송합니다"}},
  {pattern="^|cFF(.-)切换至%[(.-)%]形态$",parts={"|cFF",{index=1,player=false,numeric=false},"전환 대상[",{index=2,player=false,numeric=false},"]형태"}},
  {pattern="^来自粉色妖精小姐的零花钱：(.-)$",parts={"분홍 요정 아가씨가 주는 용돈.",{index=1,player=false,numeric=false}}},
  {pattern="^法术加成%[(.-)%((.-)%)%%%]$",parts={"주문 보너스[",{index=1,player=false,numeric=false},"(",{index=2,player=false,numeric=false},")%]"}},
  {pattern="^魔王天囚%-怪物伤害倍率:(.-)$",parts={"마왕 천수-몬스터 피해 배율.",{index=1,player=false,numeric=false}}},
  {pattern="^可复制存钱罐%-获得追忆值(.-)$",parts={"복제 가능한 저금통-추억 수치 획득",{index=1,player=false,numeric=false},""}},
  {pattern="^%[言出法随%]获得积分:([%+%-]?[%d%.]+%%?)$",parts={"[언출법수] 획득 포인트.",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)%[风云%]两线兼修已开启$",parts={{index=1,player=false,numeric=false},"[풍운] 두 계통 겸수가 개방되었습니다"}},
  {pattern="^(.-)在星球地表引发了空间震……$",parts={{index=1,player=true,numeric=false},"행성 표면에 공간진이 발생했습니다……"}},
  {pattern="^%[命运之扉%]希望计数:([%+%-]?[%d%.]+%%?)$",parts={"[운명의 문] 희망 수치.",{index=1,player=false,numeric=true}}},
  {pattern="^%[宇宙冷漠%]剩余次数：([%+%-]?[%d%.]+%%?)$",parts={"[우주의 무관심] 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^%[虚空形态%]剩余次数:([%+%-]?[%d%.]+%%?)$",parts={"[공허 형태] 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^「官人你的求签结果是【(.-)】」$",parts={"「나리의 점괘는 【",{index=1,player=false,numeric=false},"】」"}},
  {pattern="^%[稀世珍宝%]十连结果:(.-)$",parts={"[희세의 보물] 열 번 뽑기 결과.",{index=1,player=false,numeric=false}}},
  {pattern="^%[长眠之棺%]临时护盾:(.-)$",parts={"[영면의 관] 임시 보호막.",{index=1,player=false,numeric=false}}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)体力恢复$",parts={"[지령전] 체력 회복 ",{index=1,player=false,numeric=true}," 증가"}},
  {pattern="^%[地灵殿%]提升([%+%-]?[%d%.eE]+)体力上限$",parts={"[지령전] 최대 체력 ",{index=1,player=false,numeric=true}," 증가"}},
  {pattern="^幻想乡%-P点数量:([%+%-]?[%d%.eE]+)%(累积:([%+%-]?[%d%.eE]+)%)$",parts={"환상향-P 포인트. ",{index=1,player=false,numeric=true},"(누적. ",{index=2,player=false,numeric=true},")"}},
  {pattern="^%[奇遇%]获得追忆值:(.-)$",parts={"[기연] 추억 수치 획득.",{index=1,player=false,numeric=false}}},
  {pattern="^更换技术突破项目%[(.-)%]$",parts={"기술 돌파 항목 변경[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^茉子：怎么没看到(.-)大人呢？$",parts={"마코. 왜 안 보이지",{index=1,player=true,numeric=false},"어른은 어디 있어?"}},
  {pattern="^配置缺少 itemid：(.-)$",parts={"설정에 itemid가 없습니다.",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)在技术突破时触发灵光一闪$",parts={{index=1,player=true,numeric=false},"기술 돌파 중 번뜩이는 영감이 떠올랐습니다."}},
  {pattern="^(.-)完美通过了无极老师的训练$",parts={{index=1,player=true,numeric=false},"무극 선생님의 훈련을 완벽하게 통과했습니다."}},
  {pattern="^训练完成,总计命中次数：([%+%-]?[%d%.]+%%?)$",parts={"훈련 완료, 총 명중 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^购买成功 当前消耗积分：([%+%-]?[%d%.]+%%?)$",parts={"구매 완료. 현재 소모 포인트 · ",{index=1,player=false,numeric=true}}},
  {pattern="^【 (.-) 】已将村雨归还无极$",parts={"【 ",{index=1,player=true,numeric=false}," 】무라사메를 무극에게 돌려주었습니다"}},
  {pattern="^鬼丸国纲提升生命上限：([%+%-]?[%d%.]+%%?)点$",parts={"오니마루 쿠니츠나의 최대 생명력 증가량.",{index=1,player=false,numeric=true},""}},
  {pattern="^鬼丸国纲汲取了([%+%-]?[%d%.]+%%?)点生命上限$",parts={"오니마루 쿠니츠나가 흡수했습니다",{index=1,player=false,numeric=true},"최대 생명력"}},
  {pattern="^灵力值不足，所需灵力值：([%+%-]?[%d%.]+%%?)$",parts={"영력 부족, 필요 영력.",{index=1,player=false,numeric=true},""}},
  {pattern="^世界之翼庇护,剩余次数:([%+%-]?[%d%.]+%%?)$",parts={"세계의 날개 가호, 남은 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^积分不足,所需杀敌积分:(.-)$",parts={"포인트 부족, 필요한 처치 포인트.",{index=1,player=false,numeric=false},""}},
  {pattern="^尼欧斯的桂冠%-提升(.-)神性$",parts={"네오스의 월계관-증가",{index=1,player=false,numeric=false},"신성"}},
  {pattern="^可复制存钱罐%-获得积分(.-)$",parts={"복제 가능한 저금통-포인트 획득",{index=1,player=false,numeric=false},""}},
  {pattern="^小蓝帮你堆到了%[(.-)%],(.-)$",parts={"라돈이 덱에서 묘지로 보낸 카드 [",{index=1,player=false,numeric=false},"],",{index=2,player=false,numeric=false}}},
  {pattern="^%[孔涛罗%]复仇成功:(.-)$",parts={"[쿵 타오뤄] 복수 성공.",{index=1,player=false,numeric=false},""}},
  {pattern="^%[孔涛罗%]复仇失败:(.-)$",parts={"[쿵 타오뤄] 복수 실패.",{index=1,player=false,numeric=false},""}},
  {pattern="^%[阿露希%]CP点数:(.-)$",parts={"[아루시] CP 포인트.",{index=1,player=false,numeric=false},""}},
  {pattern="^解锁第(.-)层鬼域需要(.-)点鬼计数$",parts={"해금. 제",{index=1,player=false,numeric=false},"중첩 귀역에 필요한 수치",{index=2,player=false,numeric=false},"귀신 수치"}},
  {pattern="^灵基突破成功 当前次数：([%+%-]?[%d%.]+%%?)$",parts={"영기 돌파 성공. 현재 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^%[亚波伦%]复活次数:([%+%-]?[%d%.]+%%?)$",parts={"[아폴리온] 부활 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^麦哲伦%-考察成果获取([%+%-]?[%d%.]+%%?)点$",parts={"마젤란 - 조사 성과 획득",{index=1,player=false,numeric=true},""}},
  {pattern="^%[机械手臂%]已销毁:(.-)$",parts={"[기계 팔] 파괴 완료.",{index=1,player=false,numeric=false},""}},
  {pattern="^水之星不足，需求数量：([%+%-]?[%d%.]+%%?)个$",parts={"물의 별 부족, 필요 수량.",{index=1,player=false,numeric=true},"개"}},
  {pattern="^%[庭院之门%]收割(.-)成功$",parts={"[정원의 문] 수확",{index=1,player=false,numeric=false},"성공"}},
  {pattern="^阿撒托斯之核%-激活:([%+%-]?[%d%.]+%%?)秒$",parts={"아자토스의 핵-활성화.",{index=1,player=false,numeric=true},"초"}},
  {pattern="^原料不足：(.-)（需要([%+%-]?[%d%.eE]+)，当前([%+%-]?[%d%.eE]+)）$",parts={"재료 부족. ",{index=1,player=false,numeric=false},"(필요 ",{index=2,player=false,numeric=true},", 보유 ",{index=3,player=false,numeric=true},")"}},
  {pattern="^%[侵犯次数%]([%+%-]?[%d%.eE]+)%(共([%+%-]?[%d%.eE]+)人%)$",parts={"[침범 횟수]",{index=1,player=false,numeric=true},"(총 ",{index=2,player=false,numeric=true},"명)"}},
  {pattern="^当前积分:([%+%-]?[%d%.eE]+)  免费十连:([%+%-]?[%d%.eE]+)$",parts={"현재 포인트. ",{index=1,player=false,numeric=true}," / 무료 열 번 뽑기. ",{index=2,player=false,numeric=true},""}},
  {pattern="^%[风云%](.-)达到第([%+%-]?[%d%.eE]+)段修炼$",parts={"[풍운] ",{index=1,player=false,numeric=false}," 수련 ",{index=2,player=false,numeric=true},"단계 도달"}},
  {pattern="^图纸%[(.-)%((.-)%%%)%]$",parts={"설계도[",{index=1,player=false,numeric=false},"(",{index=2,player=false,numeric=false},"%)]"}},
  {pattern="^%[奇遇%]获得积分:(.-)$",parts={"[기연] 포인트 획득.",{index=1,player=false,numeric=false}}},
  {pattern="^%[奇遇%]提升等级:(.-)$",parts={"[기연] 레벨 증가.",{index=1,player=false,numeric=false}}},
  {pattern="^当前律行之履效果:(.-)%%$",parts={"현재 율행의 신발 효과.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^铃仙%-剪影枪械数量：([%+%-]?[%d%.]+%%?)$",parts={"레이센-실루엣 총기 수.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)在板条箱里面搜出来金条$",parts={{index=1,player=true,numeric=false},"나무 상자에서 금괴를 찾았습니다"}},
  {pattern="^圣代剩余杀敌奖励次数：([%+%-]?[%d%.]+%%?)$",parts={"선데 아이스크림 남은 처치 보상 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^移动速度([%+%-]?[%d%.]+%%?)=%[([%+%-]?[%d%.]+%%?)%+([%+%-]?[%d%.]+%%?)%]$",parts={"이동 속도",{index=1,player=false,numeric=true},"=[",{index=2,player=false,numeric=true},"+",{index=3,player=false,numeric=true},"]"}},
  {pattern="^总血统浓度:(.-)%%/(.-)%%$",parts={"총 혈통 농도.",{index=1,player=false,numeric=false},"%/",{index=2,player=false,numeric=false},"%"}},
  {pattern="^([%+%-]?[%d%.]+%%?)从痛苦中得到了解脱……$",parts={{index=1,player=false,numeric=true},"고통에서 해방되었습니다……"}},
  {pattern="^破势命中次数：([%+%-]?[%d%.]+%%?)%-%-(.-)$",parts={"기세 파괴 명중 횟수.",{index=1,player=false,numeric=true},"--",{index=2,player=true,numeric=false}}},
  {pattern="^真理裁决 %- 第零界$",parts={"진리의 심판 - 제","영","계"}},
  {pattern="^御守%-抵挡(.-)次高塔诅咒$",parts={"부적-방어",{index=1,player=false,numeric=false},"회 탑의 저주"}},
  {pattern="^翡翠石板%-词条获取:(.-)$",parts={"에메랄드 석판-태그 획득.",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)达到了【心剑合一】之境$",parts={{index=1,player=true,numeric=false},"【심검합일】의 경지에 도달했습니다"}},
  {pattern="^%[萝莉神%]提升(.-)属性$",parts={"[로리신] 증가",{index=1,player=false,numeric=false},"능력치"}},
  {pattern="^%[鬼火%]当前模式：(.-)$",parts={"[귀화] 현재 모드.",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)尸体被发现，(.-)被杀害了！$",parts={{index=1,player=false,numeric=false},"시체가 발견되었습니다.",{index=2,player=false,numeric=false},"살해당했습니다!"}},
  {pattern="^(.-)%[弹丸论破%](.-)结局：(.-)$",parts={{index=1,player=false,numeric=false},"[단간론파]",{index=2,player=false,numeric=false},"결말.",{index=3,player=false,numeric=false},""}},
  {pattern="^(.-)%[风云%]获得终端：(.-)$",parts={{index=1,player=false,numeric=false},"[풍운] 단말 획득.",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)%[风云%]主修选择：(.-)$",parts={{index=1,player=false,numeric=false},"[풍운] 주 수련 선택.",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)%[风云%]兼修开启：(.-)$",parts={{index=1,player=false,numeric=false},"[풍운] 겸수 개방.",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)被尤格%.索托斯祝福了$",parts={{index=1,player=true,numeric=false},"요그 소토스의 축복을 받았습니다"}},
  {pattern="^过波奖励:(.-)积分与(.-)追忆值$",parts={"웨이브 보상. 포인트 ",{index=1,player=false,numeric=false}," 및 추억 수치 ",{index=2,player=false,numeric=false},""}},
  {pattern="^【邻里友好交流次数%(已反抗%)】([%+%-]?[%d%.eE]+)$",parts={"【이웃과의 친선 교류 횟수(저항 횟수)】",{index=1,player=false,numeric=true},""}},
  {pattern="^%[遇到小红帽次数%]([%+%-]?[%d%.eE]+)$",parts={"[빨간 모자를 만난 횟수]",{index=1,player=false,numeric=true},""}},
  {pattern="^%[曹髦%]道心提升至([%+%-]?[%d%.eE]+)$",parts={"[조모] 도심 ",{index=1,player=false,numeric=true},"까지 증가"}},
  {pattern="^当前词条：%[ (.-) %]$",parts={"현재 태그. [ ",{index=1,player=false,numeric=false}," ]"}},
  {pattern="^%[系统%]贷款增加了([%+%-]?[%d%.eE]+)$",parts={"[시스템] 대출 ",{index=1,player=false,numeric=true}," 증가"}},
  {pattern="^奈亚拉幻形当前词条:(.-)$",parts={"니알라 환형의 현재 태그.",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)获得称号《并非人类》$",parts={{index=1,player=true,numeric=false},"칭호 《인간이 아닌 자》 획득"}},
  {pattern="^(.-) 运行能源消耗:(.-)/秒$",parts={"",{index=1,player=false,numeric=false}," 가동 에너지 소모.",{index=2,player=false,numeric=false},"/초"}},
  {pattern="^本次收获%(共挖掘(.-)次%): (.-)$",parts={"이번 수확(총 발굴",{index=1,player=false,numeric=false},"회). ",{index=2,player=false,numeric=false}}},
  {pattern="^(.-)使用了春秋蝉逆转时空$",parts={{index=1,player=true,numeric=false},"춘추선으로 시공을 되돌렸습니다."}},
  {pattern="^『(.-)的诅咒爆发了……』$",parts={"『",{index=1,player=true,numeric=false},"의 저주가 폭발했습니다……』"}},
  {pattern="^成功,进度改变:(.-)%%$",parts={"성공, 진도 변화.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^失败,进度改变:(.-)%%$",parts={"실패, 진도 변화.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^能源不足,所需能源:(.-)$",parts={"에너지 부족, 필요한 에너지.",{index=1,player=false,numeric=false},""}},
  {pattern="^积分不足 所需积分：([%+%-]?[%d%.]+%%?)$",parts={"포인트 부족, 필요 포인트.",{index=1,player=false,numeric=true}}},
  {pattern="^积分不足 所需积分：(.-)$",parts={"포인트 부족, 필요 포인트.",{index=1,player=false,numeric=false}}},
  {pattern="^兑换成功 剩余军功：([%+%-]?[%d%.]+%%?)$",parts={"교환 성공, 남은 군공.",{index=1,player=false,numeric=true}}},
  {pattern="^军功不足 当前军功：([%+%-]?[%d%.]+%%?)$",parts={"군공 부족, 현재 군공.",{index=1,player=false,numeric=true}}},
  {pattern="^回收成功 剩余军功：([%+%-]?[%d%.]+%%?)$",parts={"회수 성공, 남은 군공.",{index=1,player=false,numeric=true}}},
  {pattern="^绯提升伤害加成：([%+%-]?[%d%.]+%%?)%%$",parts={"비의 피해 보너스 증가량.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^鲸者武松(.-)成功击杀海豹(.-)$",parts={"고래 사냥꾼 무송",{index=1,player=true,numeric=false},"물개를 처치했습니다",{index=2,player=true,numeric=false}}},
  {pattern="^绯汲取了([%+%-]?[%d%.]+%%?)%%伤害加成$",parts={"비가 흡수했습니다",{index=1,player=false,numeric=true},"%피해 보너스"}},
  {pattern="^%[十二星弹解锁%](.-)$",parts={"[열두 별 탄환 해금]",{index=1,player=false,numeric=false}}},
  {pattern="^小熊饼干获得追忆值:(.-)$",parts={"곰돌이 과자에서 추억 수치 획득.",{index=1,player=false,numeric=false},""}},
  {pattern="^角色基础伤害%[([%+%-]?[%d%.]+%%?)%]$",parts={"캐릭터 기본 피해[",{index=1,player=false,numeric=true},"]"}},
  {pattern="^经验获取%[([%+%-]?[%d%.]+%%?)%%%]$",parts={"경험치 획득[",{index=1,player=false,numeric=true},"%]"}},
  {pattern="^召唤加成%[(.-)%%%]$",parts={"소환 보너스[",{index=1,player=false,numeric=false},"%]"}},
  {pattern="^枪械加成%[(.-)%%%]$",parts={"총기 보너스[",{index=1,player=false,numeric=false},"%]"}},
  {pattern="^近战加成%[(.-)%%%]$",parts={"근접 보너스[",{index=1,player=false,numeric=false},"%]"}},
  {pattern="^生命修正%[(.-)%%%]$",parts={"생명력 보정[",{index=1,player=false,numeric=false},"%]"}},
  {pattern="^你获得了(.-)的分红%(总投资额:(.-)%)$",parts={"획득했습니다",{index=1,player=false,numeric=false},"의 배당금(총 투자액.",{index=2,player=false,numeric=false},")"}},
  {pattern="^当前反物质黑洞数量:(.-)$",parts={"현재 반물질 블랙홀 수.",{index=1,player=false,numeric=false}}},
  {pattern="^真理裁决 %- 第(.-)界$",parts={"진리의 심판 - 제",{index=1,player=false,numeric=false},"계"}},
  {pattern="^F技能切换为%[(.-)%]$",parts={"F 스킬 전환[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^当前药水成功率:(.-)%%$",parts={"현재 물약 성공률.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^净化石%-抵挡(.-)次诅咒$",parts={"정화석-방어",{index=1,player=false,numeric=false},"회 저주"}},
  {pattern="^以太共鸣对象已标记：(.-)$",parts={"에테르 공명 대상 표시 완료.",{index=1,player=false,numeric=false},""}},
  {pattern="^爱丽丝%-当前属性:(.-)$",parts={"앨리스-현재 능력치.",{index=1,player=false,numeric=false}}},
  {pattern="^%[储君%]铸造值:(.-)$",parts={"[왕위 계승자] 주조 수치.",{index=1,player=false,numeric=false},""}},
  {pattern="^外域物质不足%(所需(.-)点%)$",parts={"외역 물질 부족(필요량",{index=1,player=false,numeric=false},"포인트)"}},
  {pattern="^%[(.-)%]使魔创建失败$",parts={"[",{index=1,player=false,numeric=false},"]사역마 생성 실패"}},
  {pattern="^%[储君%]铸造值:([%+%-]?[%d%.]+%%?)$",parts={"[왕위 계승자] 주조 수치.",{index=1,player=false,numeric=true},""}},
  {pattern="^%[系统%](.-)装载成功(.-)$",parts={"[시스템] ",{index=1,player=false,numeric=false}," 장착 성공",{index=2,player=false,numeric=false},""}},
  {pattern="^%[(.-)%]休憩完毕%(恢复10体力与10%%生命值%),(.-)$",parts={"[",{index=1,player=false,numeric=false},"] 휴식 완료(체력 10 및 생명력 10","%"," 회복), ",{index=2,player=false,numeric=false},""}},
  {pattern="^黑色障壁剩余次数：([%+%-]?[%d%.]+%%?)$",parts={"검은 장벽 남은 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^千明可鉴剩余次数：([%+%-]?[%d%.]+%%?)$",parts={"천명가감 남은 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^奇迹之花剩余次数：([%+%-]?[%d%.]+%%?)$",parts={"기적의 꽃 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^死河之力消耗血液：([%+%-]?[%d%.]+%%?)$",parts={"사하의 힘으로 소모한 혈액.",{index=1,player=false,numeric=true},""}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)%%伤害修正$",parts={"증가했습니다",{index=1,player=false,numeric=true},"%피해 보정"}},
  {pattern="^植株年份:([%+%-]?[%d%.]+%%?)年%(%+([%+%-]?[%d%.]+%%?)%)$",parts={"식물의 수령.",{index=1,player=false,numeric=true},"년(+",{index=2,player=false,numeric=true},")"}},
  {pattern="^当前空间扭曲层数：([%+%-]?[%d%.]+%%?)$",parts={"현재 공간 왜곡 중첩 수.",{index=1,player=false,numeric=true}}},
  {pattern="^『(.-)唤起了神迹……』$",parts={"『",{index=1,player=true,numeric=false},"기적을 불러일으켰다……』"}},
  {pattern="^(.-)被星之彩所环绕……$",parts={{index=1,player=true,numeric=false},"우주에서 온 색채에 둘러싸였습니다……"}},
  {pattern="^里幻剑复活规制：([%+%-]?[%d%.]+%%?)次$",parts={"이면 환검 부활 규제.",{index=1,player=false,numeric=true},"회"}},
  {pattern="^(.-)开启了新的轮回……$",parts={{index=1,player=true,numeric=false},"새로운 윤회가 시작되었습니다……"}},
  {pattern="^剪影%-极速模块：(.-)$",parts={"실루엣-초고속 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^剪影%-升级模块：(.-)$",parts={"실루엣-강화 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^剪影%-弹匣模块：(.-)$",parts={"실루엣-탄창 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^剪影%-雷电模块：(.-)$",parts={"실루엣-번개 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^追忆值不足，需要(.-)点$",parts={"추억 수치 부족, 필요 수치",{index=1,player=false,numeric=false},""}},
  {pattern="^噬星灾神挑战次数:(.-)$",parts={"별을 삼키는 재앙신 도전 횟수.",{index=1,player=false,numeric=false},""}},
  {pattern="^空间站物资仓库: (.-)$",parts={"우주 정거장 물자 창고. ",{index=1,player=false,numeric=false}}},
  {pattern="^灾祸等级提升至Lv(.-)$",parts={"재앙 레벨 상승. Lv",{index=1,player=false,numeric=false},""}},
  {pattern="^需要消耗(.-)个灾祸药剂$",parts={"필요 소모량",{index=1,player=false,numeric=false},"개 재앙 물약"}},
  {pattern="^降低([%+%-]?[%d%.]+%%?)点基础生命上限$",parts={"감소",{index=1,player=false,numeric=true},"기본 최대 생명력"}},
  {pattern="^(.-)的小蓝成功毕业了！$",parts={{index=1,player=true,numeric=false},"의 라돈이 무사히 수료했습니다!"}},
  {pattern="^(.-)指出真正的凶手为:(.-)$",parts={{index=1,player=false,numeric=false},"진범 지목.",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)%[风云%](.-)已圆满$",parts={{index=1,player=false,numeric=false},"[풍운]",{index=2,player=false,numeric=false},"이미 완성했습니다"}},
  {pattern="^(.-)%[风云修炼%]\n(.-)$",parts={{index=1,player=false,numeric=false},"[풍운 수련]",{index=2,player=false,numeric=false},""}},
  {pattern="^%[新生触发%]:(.-)$",parts={"[신생 발동]",{index=1,player=false,numeric=false}}},
  {pattern="^%[蜕皮触发%]:(.-)$",parts={"[탈피 발동]",{index=1,player=false,numeric=false}}},
  {pattern="^积分不足,所需积分([%+%-]?[%d%.]+%%?)$",parts={"포인트 부족, 필요 포인트",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)因为太痛所以黑化了$",parts={{index=1,player=true,numeric=false},"너무 아파서 흑화했습니다"}},
  {pattern="^提升([%+%-]?[%d%.]+%%?)点基础生命上限$",parts={"증가",{index=1,player=false,numeric=true},"기본 최대 생명력"}},
  {pattern="^原料不足：(.-) 当前0$",parts={"재료 부족. ",{index=1,player=false,numeric=false}," 보유량 0"}},
  {pattern="^竜王の颚力量:([%+%-]?[%d%.eE]+)%%$",parts={"용왕의 턱 위력. ",{index=1,player=false,numeric=true},"","%",""}},
  {pattern="^%[(.-)%]探索完毕,(.-)$",parts={"[",{index=1,player=false,numeric=false},"] 탐색 완료, ",{index=2,player=false,numeric=false},""}},
  {pattern="^生命上限 ([%+%-]?[%d%.eE]+)（([%+%-]?[%d%.eE]+)%%）$",parts={"최대 생명력 ",{index=1,player=false,numeric=true},"(",{index=2,player=false,numeric=true},"","%",")"}},
  {pattern="^(.-)滑步的时候摔倒了$",parts={{index=1,player=true,numeric=false},"슬라이딩하다 넘어졌습니다"}},
  {pattern="^生命恢复提升了([%+%-]?[%d%.]+%%?)点$",parts={"생명력 회복 증가",{index=1,player=false,numeric=true},""}},
  {pattern="^([%+%-]?[%d%.]+%%?)秒后末日环境开启$",parts={{index=1,player=false,numeric=true},"초 후 종말 환경 시작"}},
  {pattern="^书籍剩余耐久度：([%+%-]?[%d%.]+%%?)$",parts={"책의 남은 내구도.",{index=1,player=false,numeric=true},""}},
  {pattern="^已经驾驭%[(.-)%]$",parts={"이미 다루는 중[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)%%抗药性$",parts={"증가했습니다",{index=1,player=false,numeric=true},"%약물 내성"}},
  {pattern="^降低了([%+%-]?[%d%.]+%%?)%%抗药性$",parts={"감소했습니다",{index=1,player=false,numeric=true},"%약물 내성"}},
  {pattern="^填充了(.-)单位的能源$",parts={"충전했습니다",{index=1,player=false,numeric=false},"만큼 에너지 충전"}},
  {pattern="^目前锻造中武器：(.-)$",parts={"현재 단조 중인 무기 · ",{index=1,player=false,numeric=false}}},
  {pattern="^当前成功率：([%+%-]?[%d%.]+%%?)%%$",parts={"현재 성공률.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^(.-)对着(.-)放了一只鸽子$",parts={{index=1,player=true,numeric=false},"에게",{index=2,player=true,numeric=false},"비둘기 한 마리를 날리고"}},
  {pattern="^(.-)被阿波菲斯杀害了$",parts={{index=1,player=true,numeric=false},"아포피스에게 살해당했습니다"}},
  {pattern="^绯焰地狱冷却：([%+%-]?[%d%.]+%%?)秒$",parts={"비염지옥 재사용 대기시간.",{index=1,player=false,numeric=true},"초"}},
  {pattern="^(.-)装备了希望之刀。$",parts={{index=1,player=true,numeric=false},"희망의 검을 장착했습니다."}},
  {pattern="^(.-)干了一杯曼陀罗汁$",parts={{index=1,player=true,numeric=false},"만다라 즙 한 잔을 마셨습니다"}},
  {pattern="^(.-) 当前仇恨目标:(.-)$",parts={"",{index=1,player=false,numeric=false}," 현재 공격 대상:",{index=2,player=false,numeric=false}}},
  {pattern="^(.-)成为我的力量吧！$",parts={{index=1,player=true,numeric=false},"내 힘이 되어라!"}},
  {pattern="^苏醒吧我的战士(.-)！$",parts={"깨어나라, 나의 전사여",{index=1,player=true,numeric=false},"！"}},
  {pattern="^二阶堂真红：(.-)%.(.-)$",parts={"니카이도 신쿠.",{index=1,player=false,numeric=false},".",{index=2,player=false,numeric=false}}},
  {pattern="^混沌系数%[([%+%-]?[%d%.]+%%?)%]$",parts={"혼돈 계수[",{index=1,player=false,numeric=true},"]"}},
  {pattern="^孤狼%-伤逝杀敌([%+%-]?[%d%.]+%%?)$",parts={"외로운 늑대-상실의 처치",{index=1,player=false,numeric=true}}},
  {pattern="^成功获得神器: (.-)$",parts={"신기 획득 성공. ",{index=1,player=false,numeric=false},""}},
  {pattern="^你喝下了(.-)%[(.-)%]$",parts={"마셨습니다",{index=1,player=false,numeric=false},"[",{index=2,player=false,numeric=false},"]"}},
  {pattern="^(.-)被自然祝福了……$",parts={{index=1,player=true,numeric=false},"자연의 축복을 받았습니다……"}},
  {pattern="^提升([%+%-]?[%d%.]+%%?)%%伤害修正$",parts={"증가",{index=1,player=false,numeric=true},"%피해 보정"}},
  {pattern="^全属性增幅:([%+%-]?[%d%.]+%%?)%%$",parts={"모든 능력치 증폭.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^进阶成功%[(.-)%]$",parts={"진급 성공 [",{index=1,player=false,numeric=false},"]"}},
  {pattern="^P点不足%(所需(.-)点%)$",parts={"P 포인트 부족(필요량",{index=1,player=false,numeric=false},"포인트)"}},
  {pattern="^喵喵~%(获得(.-)积分%)$",parts={"야옹야옹~(획득",{index=1,player=false,numeric=false},"포인트)"}},
  {pattern="^%[外域启示%](.-)$",parts={"[외역의 계시]",{index=1,player=false,numeric=false}}},
  {pattern="^提升(.-)%%伤害加成$",parts={"증가",{index=1,player=false,numeric=false},"%피해 보너스"}},
  {pattern="^提升(.-)%%终结伤害$",parts={"증가",{index=1,player=false,numeric=false},"%종결 피해"}},
  {pattern="^任务:击杀(.-)个敌人$",parts={"임무. 처치",{index=1,player=false,numeric=false},"명 적"}},
  {pattern="^%[(.-)%%%]探索(.-)$",parts={"[",{index=1,player=false,numeric=false},"","%","] 탐색",{index=2,player=false,numeric=false},""}},
  {pattern="^药水成功率 ([%+%-]?[%d%.eE]+)%%$",parts={"물약 성공률 ",{index=1,player=false,numeric=true},"","%",""}},
  {pattern="^当前波次%(#([%+%-]?[%d%.eE]+)%):$",parts={"현재 웨이브(#",{index=1,player=false,numeric=true},")."}},
  {pattern="^坐标：([%+%-]?[%d%.eE]+)，([%+%-]?[%d%.eE]+)(.-)；范围([%+%-]?[%d%.eE]+)(.-)码$",parts={"좌표. ",{index=1,player=false,numeric=true},", ",{index=2,player=false,numeric=true},"",{index=3,player=false,numeric=false}," / 범위 ",{index=4,player=false,numeric=true},"",{index=5,player=false,numeric=false},""}},
  {pattern="^%[sen值%]([%+%-]?[%d%.eE]+)$",parts={"[sen 수치]",{index=1,player=false,numeric=true},""}},
  {pattern="^%[誓约点数%]([%+%-]?[%d%.eE]+)$",parts={"[서약 포인트]",{index=1,player=false,numeric=true},""}},
  {pattern="^%[相爱次数%]([%+%-]?[%d%.eE]+)$",parts={"[서로 사랑한 횟수]",{index=1,player=false,numeric=true},""}},
  {pattern="^%[杀害数量%]([%+%-]?[%d%.eE]+)$",parts={"[살해 수]",{index=1,player=false,numeric=true},""}},
  {pattern="^复写效果对象：(.-)$",parts={"복제 효과 대상.",{index=1,player=false,numeric=false}}},
  {pattern="^拟态结束对象：(.-)$",parts={"의태 종료 대상.",{index=1,player=false,numeric=false}}},
  {pattern="^妖化剩余次数：([%+%-]?[%d%.]+%%?)$",parts={"요괴화 남은 횟수.",{index=1,player=false,numeric=true}}},
  {pattern="^灵力剩余:([%+%-]?[%d%.]+%%?)%%$",parts={"남은 영력:",{index=1,player=false,numeric=true},"%"}},
  {pattern="^污染强度:([%+%-]?[%d%.]+%%?)%%$",parts={"오염 강도:",{index=1,player=false,numeric=true},"%"}},
  {pattern="^「丧钟」剩余(.-)发$",parts={"「죽음의 종」 남은 수량",{index=1,player=false,numeric=false},"발"}},
  {pattern="^美丽之物点数：([%+%-]?[%d%.]+%%?)$",parts={"아름다운 것 포인트.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)抢走了(.-)的棒棒糖$",parts={{index=1,player=true,numeric=false},"빼앗았습니다",{index=2,player=false,numeric=false},"의 막대사탕"}},
  {pattern="^(.-)建立了链接通道$",parts={{index=1,player=true,numeric=false},"연결 통로가 만들어졌습니다"}},
  {pattern="^(.-)随风飘逝了……$",parts={{index=1,player=true,numeric=false},"바람을 따라 흩어졌습니다……"}},
  {pattern="^无效配方序号：(.-)$",parts={"잘못된 조합법 번호.",{index=1,player=false,numeric=false},""}},
  {pattern="^当前进度:(.-)%%$",parts={"현재 진도.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点全属性$",parts={"증가했습니다",{index=1,player=false,numeric=true},"모든 능력치"}},
  {pattern="^(.-)开启了神话箱:$",parts={{index=1,player=true,numeric=false},"신화 상자를 열었습니다."}},
  {pattern="^并发出了(.-)的声音$",parts={"이렇게 소리쳤습니다. ",{index=1,player=false,numeric=false},"!"}},
  {pattern="^剩余躯体数量:([%+%-]?[%d%.]+%%?)$",parts={"남은 육체 수.",{index=1,player=false,numeric=true}}},
  {pattern="^你是%[(.-)%]：$",parts={"당신은 [",{index=1,player=false,numeric=false},"]："}},
  {pattern="^伤害加成：([%+%-]?[%d%.]+%%?)%%$",parts={"피해 보너스.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^(.-)准备多停留一会$",parts={{index=1,player=true,numeric=false},"체류 연장 준비"}},
  {pattern="^(.-)投掷了命运金币$",parts={{index=1,player=true,numeric=false},"운명의 동전을 던졌습니다"}},
  {pattern="^龙血浓度:([%+%-]?[%d%.]+%%?)%%$",parts={"용혈 농도.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^神之花瓣碎片：(.-)$",parts={"신의 꽃잎 파편.",{index=1,player=false,numeric=false},""}},
  {pattern="^魔之原质碎片：(.-)$",parts={"악마의 원질 파편.",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)，时代已经变了$",parts={{index=1,player=true,numeric=false},", 시대가 변했다"}},
  {pattern="^气值:([%+%-]?[%d%.]+%%?)/100$",parts={"기 수치.",{index=1,player=false,numeric=true},"/100"}},
  {pattern="^(.-)被选定为破界者$",parts={{index=1,player=true,numeric=false},"경계 파괴자로 선택되었습니다"}},
  {pattern="^二阶堂真红： (.-)$",parts={"니카이도 신쿠. ",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)掷出了([%+%-]?[%d%.]+%%?)点%(上限([%+%-]?[%d%.]+%%?)%)$",parts={{index=1,player=true,numeric=false},"굴렸습니다",{index=2,player=false,numeric=true},"만큼(상한",{index=3,player=false,numeric=true},")"}},
  {pattern="^累积现世神兵：(.-)$",parts={"누적 현현 신병.",{index=1,player=false,numeric=false}}},
  {pattern="^角色基础伤害：([%+%-]?[%d%.]+%%?)$",parts={"캐릭터 기본 피해.",{index=1,player=false,numeric=true}}},
  {pattern="^获得变异：【(.-)】$",parts={"변이 획득.【",{index=1,player=false,numeric=false},"】"}},
  {pattern="^变身冷却完毕:(.-)$",parts={"변신 재사용 대기 완료.",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)被砸矮了3厘米$",parts={{index=1,player=true,numeric=false},"얻어맞아 키가 3센티미터 줄었습니다"}},
  {pattern="^当前观星计数:([%+%-]?[%d%.]+%%?)$",parts={"현재 별 관측 카운트.",{index=1,player=false,numeric=true},""}},
  {pattern="^伤害加成:([%+%-]?[%d%.]+%%?)%%$",parts={"피해 증가량.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^经验获取:([%+%-]?[%d%.]+%%?)%%$",parts={"경험치 획득.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^杀敌成长:(.-)%%$",parts={"처치 성장.",{index=1,player=false,numeric=false},"%"}},
  {pattern="^(.-)案件凶手指向:(.-)$",parts={{index=1,player=false,numeric=false},"사건의 범인으로 지목된 대상.",{index=2,player=false,numeric=false},""}},
  {pattern="^【住客%(上限([%+%-]?[%d%.]+%%?)%)】(.-)$",parts={"【투숙객(상한",{index=1,player=false,numeric=true},")】",{index=2,player=false,numeric=false}}},
  {pattern="^与(.-)进行对话……$",parts={"와 ",{index=1,player=false,numeric=false},"대화합니다……"}},
  {pattern="^与(.-)缔结誓约……$",parts={"와 ",{index=1,player=false,numeric=false},"서약을 맺습니다……"}},
  {pattern="^(.-)柏青哥中了大奖$",parts={{index=1,player=true,numeric=false},"파칭코 대박 당첨"}},
  {pattern="^处理了与(.-)的事务$",parts={"업무를 처리한 대상",{index=1,player=true,numeric=false},"관련 업무"}},
  {pattern="^提升(.-)%%全属性$",parts={"증가",{index=1,player=false,numeric=false},"%모든 능력치"}},
  {pattern="^等级变化：([%+%-]?[%d%.eE]+) 级$",parts={"레벨 변화. ",{index=1,player=false,numeric=true}," 레벨"}},
  {pattern="^过波奖励:(.-)积分$",parts={"웨이브 보상. 포인트 ",{index=1,player=false,numeric=false},""}},
  {pattern="^%[冒险点%]([%+%-]?[%d%.eE]+)$",parts={"[모험 포인트]",{index=1,player=false,numeric=true},""}},
  {pattern="^当前DPS:([%+%-]?[%d%.]+%%?)$",parts={"현재 DPS.",{index=1,player=false,numeric=true}}},
  {pattern="^狂暴度：无穷(.-)$",parts={"광폭도. 무한",{index=1,player=false,numeric=false},""}},
  {pattern="^狂暴度：([%+%-]?[%d%.]+%%?)%%$",parts={"광폭도.",{index=1,player=false,numeric=true},"%"}},
  {pattern="^([%+%-]?[%d%.]+%%?)秒后切换环境$",parts={{index=1,player=false,numeric=true},"초 후 환경 전환"}},
  {pattern="^图纸%[(.-)%]$",parts={"설계도[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^植株年份:([%+%-]?[%d%.]+%%?)年$",parts={"식물의 수령.",{index=1,player=false,numeric=true},"년"}},
  {pattern="^驾驭%[(.-)%]$",parts={"다루기[",{index=1,player=false,numeric=false},"]"}},
  {pattern="^提升了(.-)点属性$",parts={"증가했습니다",{index=1,player=false,numeric=false},"능력치"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点属性$",parts={"증가했습니다",{index=1,player=false,numeric=true},"능력치"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点护甲$",parts={"증가했습니다",{index=1,player=false,numeric=true},"방어력"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点力量$",parts={"증가했습니다",{index=1,player=false,numeric=true},"힘"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点敏捷$",parts={"증가했습니다",{index=1,player=false,numeric=true},"민첩"}},
  {pattern="^提升了([%+%-]?[%d%.]+%%?)点智力$",parts={"증가했습니다",{index=1,player=false,numeric=true},"지능"}},
  {pattern="^射击模式%-(.-)$",parts={"사격 모드-",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)被怪物杀害了$",parts={{index=1,player=true,numeric=false},"몬스터에게 살해당했습니다"}},
  {pattern="^当前灵力值：([%+%-]?[%d%.]+%%?)$",parts={"현재 영력.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)装备了铁刀。$",parts={{index=1,player=true,numeric=false},"철도를 장착했습니다."}},
  {pattern="^冷却完毕%-(.-)$",parts={"재사용 대기 완료-",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)准备紧急起飞$",parts={{index=1,player=true,numeric=false},"긴급 출항 준비"}},
  {pattern="^幸运%[([%+%-]?[%d%.]+%%?)%]$",parts={"행운[",{index=1,player=false,numeric=true},"]"}},
  {pattern="^剩余刷新:(.-)次$",parts={"남은 새로고침.",{index=1,player=false,numeric=false},"회"}},
  {pattern="^剩余天赋点：(.-)$",parts={"남은 재능 포인트.",{index=1,player=false,numeric=false}}},
  {pattern="^剩余天赋点：([%+%-]?[%d%.]+%%?)$",parts={"남은 재능 포인트.",{index=1,player=false,numeric=true}}},
  {pattern="^剩余追忆值:(.-)$",parts={"남은 추억 수치:",{index=1,player=false,numeric=false}}},
  {pattern="^怪物强度:(.-)级$",parts={"몬스터 강도.",{index=1,player=false,numeric=false},"레벨"}},
  {pattern="^剩余神化位：([%+%-]?[%d%.]+%%?)$",parts={"남은 신화 슬롯.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)(.-) 当前数量：(.-)(.-)$",parts={{index=1,player=false,numeric=false},{index=2,player=false,numeric=false}," 현재 수량.",{index=3,player=false,numeric=false},{index=4,player=false,numeric=false},""}},
  {pattern="^额外召唤物:([%+%-]?[%d%.]+%%?)$",parts={"추가 소환물.",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)死于身体崩坏$",parts={{index=1,player=true,numeric=false},"신체 붕괴로 사망"}},
  {pattern="^时钟计数：([%+%-]?[%d%.]+%%?)点$",parts={"시계 수치.",{index=1,player=false,numeric=true},""}},
  {pattern="^提升([%+%-]?[%d%.]+%%?)点全属性$",parts={"증가",{index=1,player=false,numeric=true},"모든 능력치"}},
  {pattern="^把(.-)和(.-)变成了(.-)和(.-)$",parts={"",{index=1,player=false,numeric=false},"와 ",{index=2,player=false,numeric=false},"으로 바꿨습니다",{index=3,player=false,numeric=false},"와 ",{index=4,player=false,numeric=false}}},
  {pattern="^剑神(.-)出山了！$",parts={"검신",{index=1,player=true,numeric=false},"출사한다!"}},
  {pattern="^(.-)成为了测量者$",parts={{index=1,player=true,numeric=false},"측량자가 되었습니다."}},
  {pattern="^全属性 ([%+%-]?[%d%.eE]+)%%$",parts={"모든 능력치 ",{index=1,player=false,numeric=true},"","%",""}},
  {pattern="^理智值:([%+%-]?[%d%.eE]+)%%$",parts={"이성 수치. ",{index=1,player=false,numeric=true},"","%",""}},
  {pattern="^#([%+%-]?[%d%.eE]+) 危险星团$",parts={"#",{index=1,player=false,numeric=true}," 위험 성단"}},
  {pattern="^【营业额%(已创收%)】([%+%-]?[%d%.eE]+)$",parts={"【매출(누적 수익)】",{index=1,player=false,numeric=true},""}},
  {pattern="^【好评数%(已收割%)】([%+%-]?[%d%.eE]+)$",parts={"【호평 수(수확 완료)】",{index=1,player=false,numeric=true},""}},
  {pattern="^【差评数%(已逃跑%)】([%+%-]?[%d%.eE]+)$",parts={"【악평 수(도망 횟수)】",{index=1,player=false,numeric=true},""}},
  {pattern="^极意层数:([%+%-]?[%d%.]+%%?)$",parts={"극의 중첩 수.",{index=1,player=false,numeric=true},""}},
  {pattern="^拟态对象：(.-)$",parts={"의태 대상.",{index=1,player=false,numeric=false}}},
  {pattern="^([%+%-]?[%d%.]+%%?)秒后下一波$",parts={"",{index=1,player=false,numeric=true},"초 후 다음 라운드"}},
  {pattern="^剩余怪物:([%+%-]?[%d%.]+%%?)$",parts={"남은 몬스터.",{index=1,player=false,numeric=true}}},
  {pattern="^枪口模块:(.-)$",parts={"총구 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^下挂模块:(.-)$",parts={"하부 부착 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^弹匣模块:(.-)$",parts={"탄창 모듈.",{index=1,player=false,numeric=false}}},
  {pattern="^神之花瓣(.-)%(来自碎片%)$",parts={"신의 꽃잎",{index=1,player=false,numeric=false},"(파편에서 획득)"}},
  {pattern="^魔之原质(.-)%(来自碎片%)$",parts={"악마의 원질",{index=1,player=false,numeric=false},"(파편에서 획득)"}},
  {pattern="^当前词条:(.-)$",parts={"현재 태그.",{index=1,player=false,numeric=false},""}},
  {pattern="^酒叠加值：([%+%-]?[%d%.]+%%?)$",parts={"술 누적 수치.",{index=1,player=false,numeric=true},""}},
  {pattern="^未知站点：(.-)$",parts={"알 수 없는 시설.",{index=1,player=false,numeric=false},""}},
  {pattern="^所需积分：([%+%-]?[%d%.]+%%?)$",parts={"필요 포인트.",{index=1,player=false,numeric=true}}},
  {pattern="^命中次数：([%+%-]?[%d%.]+%%?)$",parts={"명중 횟수.",{index=1,player=false,numeric=true},""}},
  {pattern="^消耗积分：([%+%-]?[%d%.]+%%?)$",parts={"소모 포인트 · ",{index=1,player=false,numeric=true}}},
  {pattern="^生命恢复：(.-)$",parts={"생명력 회복.",{index=1,player=false,numeric=false},""}},
  {pattern="^额外移速：(.-)$",parts={"추가 이동 속도.",{index=1,player=false,numeric=false},""}},
  {pattern="^切换失败：(.-)$",parts={"변경 실패 · ",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)获得了赐福$",parts={{index=1,player=true,numeric=false},"축복을 받았습니다"}},
  {pattern="^购买成功：(.-)$",parts={"구매 완료 · ",{index=1,player=false,numeric=false},""}},
  {pattern="^打劫成功：(.-)$",parts={"강탈 성공 · ",{index=1,player=false,numeric=false},""}},
  {pattern="^龙血纯度:(.-)$",parts={"용혈 순도.",{index=1,player=false,numeric=false}}},
  {pattern="^剩余积分:([%+%-]?[%d%.]+%%?)$",parts={"남은 포인트:",{index=1,player=false,numeric=true}}},
  {pattern="^剩余残机:([%+%-]?[%d%.]+%%?)$",parts={"남은 잔기:",{index=1,player=false,numeric=true}}},
  {pattern="^山姆锁定：(.-)$",parts={"샘의 고정 대상.",{index=1,player=true,numeric=false}}},
  {pattern="^受击层数：(.-)(.-)$",parts={"피격 중첩 수.",{index=1,player=false,numeric=false},"",{index=2,player=false,numeric=false}}},
  {pattern="^次元斩%.(.-)$",parts={"","차원참",".",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)取消了准备$",parts={{index=1,player=false,numeric=false},"준비를 취소했습니다"}},
  {pattern="^神化数量：([%+%-]?[%d%.]+%%?)$",parts={"신화 수.",{index=1,player=false,numeric=true}}},
  {pattern="^传奇数量：([%+%-]?[%d%.]+%%?)$",parts={"전설 수.",{index=1,player=false,numeric=true}}},
  {pattern="^落樱点数：([%+%-]?[%d%.]+%%?)$",parts={"낙화 포인트.",{index=1,player=false,numeric=true},""}},
  {pattern="^你想要吃掉(.-)$",parts={"먹으려 합니다",{index=1,player=true,numeric=false}}},
  {pattern="^(.-)拒绝被吃掉$",parts={{index=1,player=true,numeric=false},"먹히기 거부"}},
  {pattern="^阿福揍扁了(.-)$",parts={"아푸가 때려눕혔습니다. ",{index=1,player=false,numeric=false}}},
  {pattern="^提升([%+%-]?[%d%.]+%%?)点属性$",parts={"증가",{index=1,player=false,numeric=true},"능력치"}},
  {pattern="^体力上限:([%+%-]?[%d%.]+%%?)$",parts={"최대 스태미나.",{index=1,player=false,numeric=true},""}},
  {pattern="^额外移速:([%+%-]?[%d%.]+%%?)$",parts={"추가 이동 속도.",{index=1,player=false,numeric=true},""}},
  {pattern="^【名称】(.-)的(.-)$",parts={"【이름】",{index=1,player=true,numeric=false},"의",{index=2,player=false,numeric=false},""}},
  {pattern="^杀害了(.-)……$",parts={"살해했습니다",{index=1,player=false,numeric=false},"……"}},
  {pattern="^与(.-)相爱……$",parts={"와 ",{index=1,player=false,numeric=false},"서로 사랑합니다……"}},
  {pattern="^侵犯了(.-)……$",parts={"침범했습니다",{index=1,player=false,numeric=false},"……"}},
  {pattern="^(.-)的右手断了$",parts={{index=1,player=true,numeric=false},"의 오른손이 끊어졌습니다"}},
  {pattern="^(.-)获得【(.-)】%(唯一%)$",parts={{index=1,player=true,numeric=false},"획득【",{index=2,player=false,numeric=false},"】(유일)"}},
  {pattern="^|c(.-)获得了(.-)$",parts={"|c",{index=1,player=false,numeric=false},"획득했습니다",{index=2,player=false,numeric=false},""}},
  {pattern="^锁魂计数：([%+%-]?[%d%.]+%%?)$",parts={"영혼 속박 수치.",{index=1,player=false,numeric=true}}},
  {pattern="^解魂计数：([%+%-]?[%d%.]+%%?)$",parts={"영혼 해방 수치.",{index=1,player=false,numeric=true}}},
  {pattern="^当前模式：(.-)$",parts={"현재 모드. ",{index=1,player=false,numeric=false},""}},
  {pattern="^获得([%+%-]?[%d%.eE]+)点P点$",parts={"P 포인트 ",{index=1,player=false,numeric=true}," 획득"}},
  {pattern="^损失([%+%-]?[%d%.eE]+)点P点$",parts={"P 포인트 ",{index=1,player=false,numeric=true}," 상실"}},
  {pattern="^【热度%(访客数%)】([%+%-]?[%d%.eE]+)$",parts={"【인기도(방문객 수)】",{index=1,player=false,numeric=true},""}},
  {pattern="^护盾值：([%+%-]?[%d%.]+%%?)$",parts={"보호막 수치:",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)出现了！$",parts={"",{index=1,player=false,numeric=false},"등장!"}},
  {pattern="^你使用了(.-)$",parts={"사용했습니다",{index=1,player=false,numeric=false},""}},
  {pattern="^处刑值：([%+%-]?[%d%.]+%%?)$",parts={"처형 수치.",{index=1,player=false,numeric=true},""}},
  {pattern="^(.-)的命运是(.-)$",parts={{index=1,player=true,numeric=false},"의 운명은",{index=2,player=false,numeric=false},""}},
  {pattern="^冷却:([%+%-]?[%d%.]+%%?)秒$",parts={"재사용 대기시간.",{index=1,player=false,numeric=true},"초"}},
  {pattern="^(.-)因子%-(.-)$",parts={{index=1,player=false,numeric=false},"인자-",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)词条%-(.-)$",parts={{index=1,player=false,numeric=false},"옵션-",{index=2,player=false,numeric=false},""}},
  {pattern="^(.-)数量不足$",parts={"",{index=1,player=false,numeric=false},"수량이 부족합니다."}},
  {pattern="^你查验了(.-)$",parts={"조사했습니다",{index=1,player=true,numeric=false}}},
  {pattern="^山姆韧性(.-)$",parts={"샘의 강인도",{index=1,player=false,numeric=false},""}},
  {pattern="^死侍%-([%+%-]?[%d%.]+%%?)$",parts={"데드풀-",{index=1,player=false,numeric=true}}},
  {pattern="^干员:(.-)\n(.-)$",parts={"오퍼레이터:",{index=1,player=true,numeric=false},"\n",{index=2,player=false,numeric=false}}},
  {pattern="^倒计时:(.-)$",parts={"남은 시간:",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)准备完毕$",parts={{index=1,player=false,numeric=false},"준비 완료"}},
  {pattern="^(.-)被激怒了$",parts={{index=1,player=false,numeric=false},"격노했습니다"}},
  {pattern="^醉酒度：([%+%-]?[%d%.]+%%?)$",parts={"취기.",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)你过关！$",parts={{index=1,player=true,numeric=false},"통과!"}},
  {pattern="^你喝下了(.-)$",parts={"마셨습니다",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)附伤关闭$",parts={"",{index=1,player=false,numeric=false},"추가 피해 비활성화"}},
  {pattern="^(.-)附伤开启$",parts={"",{index=1,player=false,numeric=false},"추가 피해 활성화"}},
  {pattern="^(.-)被(.-)吃掉了$",parts={{index=1,player=true,numeric=false},"에게",{index=2,player=true,numeric=false},"먹혔습니다"}},
  {pattern="^把(.-)变成了(.-)$",parts={"",{index=1,player=false,numeric=false},"으로 바꿨습니다",{index=2,player=false,numeric=false}}},
  {pattern="^提升属性(.-)$",parts={"능력치 증가",{index=1,player=false,numeric=false},""}},
  {pattern="^奇迹%-(.-)$",parts={"기적 -",{index=1,player=false,numeric=false},""}},
  {pattern="^投影成功(.-)$",parts={"투영 성공",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)(.-)已被处刑$",parts={{index=1,player=false,numeric=false},{index=2,player=false,numeric=false},"이미 처형되었습니다"}},
  {pattern="^(.-)%-脱战$",parts={"",{index=1,player=false,numeric=false},"-전투 종료"}},
  {pattern="^(.-)%-入战$",parts={"",{index=1,player=false,numeric=false},"-전투 진입"}},
  {pattern="^进度：([%+%-]?[%d%.eE]+)/([%+%-]?[%d%.eE]+)(.-)$",parts={"진도. ",{index=1,player=false,numeric=true},"/",{index=2,player=false,numeric=true},"",{index=3,player=false,numeric=false},""}},
  {pattern="^枪械:(.-)(.-)$",parts={"총기.",{index=1,player=false,numeric=false},{index=2,player=false,numeric=false}}},
  {pattern="^获得了(.-)$",parts={"획득했습니다",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)爆炸了$",parts={{index=1,player=true,numeric=false},"폭발했습니다"}},
  {pattern="^(.-)杀害了(.-)$",parts={{index=1,player=true,numeric=false},"살해했습니다",{index=2,player=true,numeric=false}}},
  {pattern="^(.-)成为了(.-)$",parts={{index=1,player=true,numeric=false},"의 모습으로 변했습니다. ",{index=2,player=false,numeric=false}}},
  {pattern="^护甲：(.-)$",parts={"방어력.",{index=1,player=false,numeric=false},""}},
  {pattern="^幸运：(.-)$",parts={"행운.",{index=1,player=false,numeric=false},""}},
  {pattern="^(.-)切换至(.-)$",parts={{index=1,player=true,numeric=false},"전환 대상",{index=2,player=false,numeric=false}}},
  {pattern="^性别:([%+%-]?[%d%.]+%%?)$",parts={"성별 · ",{index=1,player=false,numeric=true}}},
  {pattern="^Ta是(.-)$",parts={"정체는",{index=1,player=false,numeric=false}}},
  {pattern="^次元斩$",parts={"","차원참",""}},
  {pattern="^(.-)该罚！$",parts={{index=1,player=true,numeric=false},"벌을 받아야겠어!"}},
  {pattern="^幸运:([%+%-]?[%d%.]+%%?)$",parts={"행운.",{index=1,player=false,numeric=true},""}},
  {pattern="^星刻：(.-)$",parts={"별의 각인.",{index=1,player=false,numeric=false}}},
  {pattern="^第(.-)波$",parts={"제",{index=1,player=false,numeric=false},"라운드"}},
  {pattern="^销毁(.-)$",parts={"파괴",{index=1,player=false,numeric=false}}},
  {pattern="^活人([%+%-]?[%d%.]+%%?)$",parts={"생존자",{index=1,player=false,numeric=true}}},
  {pattern="^(.-)：(.-)秒$",parts={"",{index=1,player=false,numeric=false},"：",{index=2,player=false,numeric=false},"초"}},
  {pattern="^(.-)死了$",parts={{index=1,player=true,numeric=false},"사망했습니다"}},
  {pattern="^第([%+%-]?[%d%.]+%%?)页$",parts={"제",{index=1,player=false,numeric=true},"페이지"}},
  {pattern="^蓄势$",parts={"","힘 모으기",""}},
  {pattern="^获得(.-)$",parts={"획득",{index=1,player=false,numeric=false}}},
  {pattern="^(.-)是(.-)$",parts={{index=1,player=false,numeric=false},"예",{index=2,player=false,numeric=false}}},
}
local M = {}
function M.translate(text, translate)
  for _,entry in ipairs(entries) do
    local values = {text:match(entry.pattern)}
    if #values > 0 then
      local result = {}
      local complete = true
      for _,part in ipairs(entry.parts) do
        if type(part) == 'string' then result[#result+1] = part
        else
          local value = values[part.index]
          if not value then complete=false;break end
          if not part.player and not part.numeric and value ~= text then value=translate(value) end
          if not part.player then
            for _,code in utf8.codes(value) do
              if code>=0x3400 and code<=0x9FFF then complete=false;break end
            end
          end
          result[#result+1]=value
        end
      end
      if complete then return table.concat(result) end
    end
  end
end
return M
